### PR TITLE
Partially fix issue when service or action introspection original message definitions was not found

### LINKED ISSUE #1966: support `.srv` and `.action` generated types for `MessageDefinition::get_full_text`.
## Description

https://github.com/ros2/rosbag2/blob/62e5f77b207471c7e3d1b8b5a887910ea079d3d9/rosbag2_cpp/src/rosbag2_cpp/message_definitions/local_message_definition_source.cpp#L208

`LocalMessageDefinitionSource` currently expects that root type file exist in the workspace, for example `ction_msgs/msg/GoalStatusArray`.
This is usually okay if that is general `.msg`, `.srv`, `.action` and `.idl` type files.
But it comes to the problem with generated files from service and action introspection such as `action_msgs/srv/CancelGoal_Event`, `example_interfaces/action/Fibonacci_FeedbackMessage`, and `example_interfaces/action/Fibonacci_GetResult_Event`, because those files do not exist in the workspace.

it eventually ends up raising `DefinitionNotFoundError`, and empty message definition is encoded in the storage.

### Expected Behavior

Originally it tries to encode the message definition information with expanding recursively in the storage, so that rosbag2 can know and manage the bag data with this encoded message definition even if original message files do not exist on the workspace.

That said, it should encode the original `.srv` and `.action` message definition as well.

### Actual Behavior

message definition will be empty for service and action introspection generate types.

## To Reproduce
1. start rosbag2 for action.

```bash
ros2 bag record --action /fibonacci
```

2. `ros2 run action_tutorials_cpp fibonacci_action_client --ros-args -p action_client_configure_introspection:=contents`
3. `ros2 run action_tutorials_py fibonacci_action_server --ros-args -p action_server_configure_introspection:=contents`

## Additional context

see https://github.com/ros2/rosbag2/issues/1964#issuecomment-2814187537

- we can break down the 2 PRs. the one is service, the other is action. so that we can backport service PR to jazzy.
- test also needs to be added with service and action introspection names to be resolved to original service and action message.

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
## Description

This PR adds a new API, `LocalMessageDefinitionSource::get_full_text_ext(root_type, topic_name)`, with a `topic_name`, to detect message definitions for services and actions introspection specific message types like `ComplexActionMsg_SendGoal_Event`, `ComplexActionMsg_GetResult_Event` and `ComplexActionMsg_FeedbackMessage`.

- Relates #1966  

### Is this user-facing behavior change?
No.

### Did you use Generative AI?
Yes. Copilot with (ChatGPT v.4.1) was used to help generate Doxygen comments and deprecation notices.

### Additional Information

- The old `LocalMessageDefinitionSource::get_full_text(root_type,)` was deprecated.
- This fix can be backported to Kilted. (API/ABI Compatible)

### Known limitation
- `get_full_text_ext()` cannot return action definition for action interface `cancel_goal` and  `status`. This issue will be resolved in a follow-up PR.

### CODE REVIEW

**Comment by Barry-Xu-2018** [comment]
The failure for [Test rosbag2 / build_and_test (pull_request)](https://github.com/ros2/rosbag2/actions/runs/15670796775/job/44141451552?pr=2041) is
```
  /__w/rosbag2/rosbag2/ros_ws/src/3hseckcxugl/rosbag2/rosbag2_py/src/rosbag2_py/_message_definitions.cpp: In function ‘void pybind11_init__message_definitions(pybind11::module_&)’:
  /__w/rosbag2/rosbag2/ros_ws/src/3hseckcxugl/rosbag2/rosbag2_py/src/rosbag2_py/_message_definitions.cpp:26:66: error: ‘rosbag2_storage::MessageDefinition rosbag2_cpp::LocalMessageDefinitionSource::get_full_text(const std::string&)’ is deprecated: Use get_full_text_ext() instead, which allows specifying the topic name and provides more flexibility in how the message definition is constructed. [-Werror=deprecated-declarations]
     26 |     "get_full_text", &rosbag2_cpp::LocalMessageDefinitionSource::get_full_text)
        |                                                                  ^~~~~~~~~~~~~
  In file included from /__w/rosbag2/rosbag2/ros_ws/src/3hseckcxugl/rosbag2/rosbag2_py/src/rosbag2_py/_message_definitions.cpp:15:
  /__w/rosbag2/rosbag2/ros_ws/install/rosbag2_cpp/include/rosbag2_cpp/rosbag2_cpp/message_definitions/local_message_definition_source.hpp:74:38: note: declared here
     74 |   rosbag2_storage::MessageDefinition get_full_text(const std::string & root_type);
        |                                      ^~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  gmake[2]: *** [CMakeFiles/_message_definitions.dir/build.make:76: CMakeFiles/_message_definitions.dir/src/rosbag2_py/_message_definitions.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:232: CMakeFiles/_message_definitions.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
  lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
  lto-wrapper: note: see the ‘-flto’ option documentation for more information
  gmake: *** [Makefile:146: all] Error 2
  ---
  Failed   <<< rosbag2_py [27.7s, exited with code 2]
```

This is due to deprecated declarations, which can cause compilation warnings and lead to failure.

rosbag2/rosbag2_py/src/rosbag2_py/_message_definitions.cpp
```c++
PYBIND11_MODULE(_message_definitions, m) {
  m.doc() = "Python wrapper of the rosbag2_cpp message definitions API";

  pybind11::class_<rosbag2_cpp::LocalMessageDefinitionSource>(
    m, "LocalMessageDefinitionSource")
  .def(pybind11::init<>())
  .def(
    "get_full_text", &rosbag2_cpp::LocalMessageDefinitionSource::get_full_text)
  .def(
    "get_full_text_ext", &rosbag2_cpp::LocalMessageDefinitionSource::get_full_text_ext);
}
```

@MichaelOrlov  
To backport to Kilted, the get_full_text() in the code above cannot be removed directly. Therefore, to solve the issue, the only option is to remove the deprecated declarations of get_full_text(). Do you have a better way ?

**Comment by MichaelOrlov** [comment]
@Barry-Xu-2018 As regards
> To backport to Kilted, the get_full_text() in the code above cannot be removed directly. Therefore, to solve the issue, the only option is to remove the deprecated declarations of get_full_text(). Do you have a better way ?

We can try to workaround it by calling `get_full_text_ext(..)` with an empty `topic_name` wrapped in a lambda on the Pybind11 layer.

**Comment by MichaelOrlov** [comment]
The ChatGPT suggests the following
```cpp
.def(
  "get_full_text",
  [](rosbag2_cpp::LocalMessageDefinitionSource &self, const std::string &root_type) {
    return self.get_full_text_ext(root_type, "");
  },
  pybind11::arg("root_type"),
  "Get full text message definition using only the root type"
)
```

**Comment by Barry-Xu-2018** [comment]
>> To backport to Kilted, the get_full_text() in the code above cannot be removed directly. Therefore, to solve the issue, the only option is to remove the deprecated declarations of get_full_text(). Do you have a better way ?
>
> We can try to workaround it by calling get_full_text_ext(..) with an empty topic_name wrapped in a lambda on the Pybind11 layer.

Thank you for your advice.

**Comment by Barry-Xu-2018** [comment]
@MichaelOrlov Please review again

File: rosbag2_py/src/rosbag2_py/_message_definitions.cpp [hunk 1]
```diff
@@ -23,5 +23,14 @@ PYBIND11_MODULE(_message_definitions, m) {
...
   .def(
-    "get_full_text", &rosbag2_cpp::LocalMessageDefinitionSource::get_full_text);
+    "get_full_text",
+    [](rosbag2_cpp::LocalMessageDefinitionSource & self, const std::string & root_type) {
+      return self.get_full_text_ext(root_type, "");
+    },
+    pybind11::arg("root_type"),
+    "The root type of the message definition. (Internally calls get_full_text_ext with an empty"
+    " topic name)"
+  )
```
Comment (MichaelOrlov) [inline rosbag2_py/src/rosbag2_py/_message_definitions.cpp]: @Barry-Xu-2018 Can you please add a deprecation warning for the `get_full_text` the similar way as I did recently in the https://github.com/ros2/rosbag2/pull/2047/commits/7ea46dd4b4a843bac287611a2a2271c81e7eb610

Comment (Barry-Xu-2018) [reply rosbag2_py/src/rosbag2_py/_message_definitions.cpp]: Thanks. I missed it. 
I updated code https://github.com/ros2/rosbag2/pull/2041/commits/a48dbc4f14a13efd12449e5eadba3513ff157176

**Comment by Barry-Xu-2018** [comment]
Rebase was done.

**Comment by Barry-Xu-2018** [comment]
Pull: #2041 
Gist:
https://gist.githubusercontent.com/Barry-Xu-2018/b7bf6ed7353257611b68a0995631452b/raw/1e87eef45d441ffc88c890d18c42c1443efab1bc/ros2_rolling.repos
BUILD args: --packages-above-and-dependencies rosbag2_cpp
TEST args: --packages-above rosbag2_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16280
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24032/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18112/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3432/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24671/)

**Review by MichaelOrlov — APPROVED** [review]
LGTM now.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted

**Review by fujitatomoya — COMMENTED** [review]
looks good to me, @Barry-Xu-2018 thanks
