### PR TITLE
Throw YAML::Exception during conversion if the data type mismatches.

### LINKED ISSUE #2256: The YAML parser of StorageOptions does not throw an exception for invalid input
## Description
When parsing YAML nodes using YAML::convert<StorageOptions>::decode(), if the input contains clearly invalid field values, no exceptions are raised, causing invalid configurations to be silently accepted.

### Expected Behavior
Throw an exception

### Actual Behavior
No exception thrown

### Test Case
```cpp
#include <gmock/gmock.h>
#include "rosbag2_storage/storage_options.hpp"
using namespace ::testing;  // NOLINT

TEST(storage_options, test)
{
  YAML::Node node;
  node["uri"] = "invalid_uri";
  node["storage_id"] = "";
  node["max_bagfile_size"] = "non_numeric_value";
  EXPECT_THROW(
    node.as<rosbag2_storage::StorageOptions>(),
    std::runtime_error);
}
```

### Output
```markdown
[ RUN      ] storage_options.test
/home/shangzh/rosbag2_ws/rosbag2/rosbag2_storage/test/rosbag2_storage/test_storage_options.cpp:11: Failure
Expected: node.as<rosbag2_storage::StorageOptions>() throws an exception of type std::runtime_error.
  Actual: it throws nothing.

[  FAILED  ] storage_options.test (0 ms)
[----------] 1 test from storage_options (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] storage_options.test

 1 FAILED TEST
```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

- Fixes #2256 

### Is this user-facing behavior change?

Yes, but barely noticeable.

### Did you use Generative AI?

No

### CODE REVIEW

File: rosbag2_storage/test/rosbag2_storage/test_storage_options.cpp [hunk 1]
```diff
@@ -54,3 +54,19 @@ TEST(storage_options, test_yaml_serialization)
   ASSERT_EQ(original.end_time_ns, reconstructed.end_time_ns);
   ASSERT_EQ(original.custom_data, reconstructed.custom_data);
 }
+
+TEST(storage_options, test_invalid_numeric_value)
+{
+  YAML::Node node;
+  node["uri"] = "some_uri";
+  node["storage_id"] = "some_identification";
+  node["max_bagfile_size"] = "non_numeric_value";
```
Comment (fujitatomoya) [inline rosbag2_storage/test/rosbag2_storage/test_storage_options.cpp:63]: this is the exact case that issue complains.
without this PR, this test fails because this cannot be converted from string to int type.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rosbag2#2262
Gist: https://gist.githubusercontent.com/fujitatomoya/2720add1a832706ccb08d8d797d53b5d/raw/de935fa174fd2fa7eee11dbe1100718f9a189864/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_storage
TEST args:  --packages-above rosbag2_storage
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17779
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26602/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20165/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6398/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26226/)

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26703/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20280/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6502/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26289/)

File: rosbag2_storage/include/rosbag2_storage/yaml.hpp [hunk 2]
```diff
@@ -42,7 +42,18 @@ template<typename T>
...
+        throw YAML::Exception(
+          node[field].Mark(),
+          "Failed to convert field '" + field + "'");
+      }
+    } catch (const YAML::Exception & ex) {
+      // Preserve original error but add field name context
+      throw YAML::Exception(
+        node[field].Mark(),
+        "Failed to convert field '" + field + "': " + ex.what());
+    }
```
Comment (MichaelOrlov) [inline rosbag2_storage/include/rosbag2_storage/yaml.hpp:53]: @fujitatomoya I am a bit confused about why you need to throw an exception, then catch it, and then rethrow it again? Can you please explain?

Maybe, would be clearer to throw an inner runtime exception, catch it and wrap it in the `YAML::Exception(..)`?

Comment (fujitatomoya) [reply rosbag2_storage/include/rosbag2_storage/yaml.hpp:53]: catch-and-rethrow pattern is intentional and serves following purpose.

`YAML::convert<T>::decode()` itself can throw its own `YAML::Exception` (e.g., for type mismatches). the catch block wraps that exception with additional context (the field name), i think this makes errors more actionable that users know which field failed, not just that something failed.

Comment (MichaelOrlov) [reply rosbag2_storage/include/rosbag2_storage/yaml.hpp:53]: @fujitatomoya Ahh got it. I think in this case, the proper solution would be 
```cpp
  if (node[field]) {
    bool converted = false;
    try {
      converted = YAML::convert<T>::decode(node[field], assign_to);
    } catch (const YAML::Exception & ex) {
      // Preserve original error but add field name context
      throw YAML::Exception(
        node[field].Mark(),
        "Failed to convert field '" + field + "': " + ex.what());
    }
    if (!converted) {
      throw YAML::Exception(node[field].Mark(), "Failed to convert field '" + field + "'");
    }
  }
```
Wouldn't you mind making proposed changes?

Comment (fujitatomoya) [reply rosbag2_storage/include/rosbag2_storage/yaml.hpp:53]: this is better and cleaner, thanks 👍

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26811/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20379/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6559/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26338/)

**Review by MichaelOrlov — APPROVED** [review]
LGTM

**Comment by fujitatomoya** [comment]
@Mergifyio backport jazzy kilted
