### PR TITLE
Address performance issue in "ros2 bag convert" when used to cut a fragment of the bag file

### LINKED ISSUE #2324: Improve performance for "ros2 bag convert"
### Issue description
The users are reporting that `ros2 bag convert` performance is not great and could be better.

For instance, in some scenarios, the recording could have 3-5 hours of data with a variety of topics. Extracting a small segment, for example, about **one minute** around the 2-3 hour mark from the start, takes a very long time to complete.
Even extracting the initial **10 seconds** from the bag can take around **7-8 minutes** on a modern laptop PC.

It is certain that the performance of the `ros2 bag convert` is suboptimal and could be improved.

### How to reproduce
For instance, if we have a bag file with around 3 hours of recording
```
Bag size:          304.7 GiB
Storage id:        mcap
ROS Distro:        unknown
Duration:          10224.890472197s
Start:             Dec  9 2025 07:35:26.984814683 (1765233326.984814683)
End:               Dec  9 2025 10:25:51.875286880 (1765243551.875286880)
Messages:          32288515
```
conversion options `output.yaml` file used to extract some messages in the time interval 
```yaml
output_bags:
- all_topics: 'true'
  end_time_ns: 1765233336984814592
  max_bagfile_size: 4000000000
  start_time_ns: 1765233326984814592
  uri: extracted
```
```bash
time ros2 bag convert -i path_to_bag/record_sensor -o output.yaml
ros2 bag convert -i  -o   289.47s user 102.70s system 88% cpu 7:21.23 total
```

### PR DESCRIPTION
**Pull request by MichaelOrlov**
## Description

This PR addresses the performance issue in `ros2 bag convert` when used to cut a fragment of the bag file.
Added the ability to limit the message range for the `ros2 bag convert` on the readout, i.e, specifying the `start_time_ns` and the `end_time_ns` for the input bags. To facilitate this functionality, a new `--input-options` CLI argument was added for the `ros2 bag convert` operation.
The newly added optional `--input-options` CLI argument refers to the YAML config file with options for input bags. Must have one top-level key "input_bags", which contains a sequence of `StorageOptions` objects. Note: either old `--input`, `-i` or new `--input-options` must be provided, but not both.

Example: cutting a time fragment from a bag:
```bash
$ ros2 bag convert --input-options input.yaml --output-options output.yaml
```

`input.yaml` - extract only messages between specific timestamps
```yaml
input_bags:
- uri: /path/to/input_bag
  storage_id: mcap
  start_time_ns: 1744227144744197147  # Start timestamp in nanoseconds since epoch
  end_time_ns: 1744227145734665546    # End timestamp in nanoseconds since epoch
```
`output.yaml`
```yaml
output_bags:
- uri: /path/to/fragment_bag
  storage_id: mcap
  all_topics: true
  all_services: true
```

Note: The `start_time_ns` and `end_time_ns` filter messages based on their timestamps (nanoseconds
since epoch). Only messages with timestamp `t` where `start_time_ns <= t <= end_time_ns` will be
included. Note that these timestamps refer to the message's receive timestamps. Before, we already had the possibility to use them for the `--output-options`. However, it will be more efficient to use the `start_time_ns` and `end_time_ns` options on the input bag rather than on the output bag, since we skip reading and processing messages out of the specified range.

- Fixes #2324

### Is this user-facing behavior change?
Yes. The user can now specify `start_time_ns` and `end_time_ns` in the newly added optional `--input-options input.yaml` file to filter messages based on their timestamps on the bag readout.

### Did you use Generative AI?
Yes, I am using GitHub Copilot, GPT-5.0 and Claude Sonet 4.5 to help with unit tests and documentation.

### Additional Information
This PR is not backportable because it has API breaking changes on the `rosbag2_py` level for the `bag_rewrite(..)` utility function.

### CODE REVIEW

File: rosbag2_transport/test/rosbag2_transport/test_rewrite.cpp [hunk 1]
```diff
@@ -248,6 +248,89 @@ TEST_P(TestRewrite, test_compress) {
...
+  while (scan_reader->has_next()) {
+    auto msg = scan_reader->read_next();
+    if (msg && msg->topic_name == "a_empty") {
+      timestamps.push_back(msg->recv_timestamp);
+    }
+  }
+  ASSERT_THAT(timestamps, SizeIs(Ge(4u)));
+
+  // Choose a mid-window based on observed timestamps
+  // Window: [input_start_time, input_end_time),
```
Comment (Barry-Xu-2018) [inline rosbag2_transport/test/rosbag2_transport/test_rewrite.cpp]: Since code is `current_timestamp <= input_end_time`

```suggestion
  // Window: [input_start_time, input_end_time],
```

**Review by Barry-Xu-2018 — APPROVED** [review]
LGTM with a minor nit

File: rosbag2_transport/test/rosbag2_transport/test_rewrite.cpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_transport/test/rosbag2_transport/test_rewrite.cpp]: Good catch. I forgot to change a comment.

File: README.md [hunk 2]
```diff
@@ -363,44 +363,69 @@ Topic information: Topic: /chatter | Type: std_msgs/String | Count: 9 | Serializ
...
 * Serialization format conversion
 * ... and more!
 
 Here is an example command:
 
-```
-ros2 bag convert --input /path/to/bag1 --input /path/to/bag2 storage_id --output-options output_options.yaml
+```shell dollar
+ros2 bag convert --input /path/to/bag1 --input /path/to/bag2 storage_id \
+  --output-options output_options.yaml
```
Comment (christophebedard) [inline README.md]: minor: `shell dollar` doesn't do anything here. The other command examples just use a `$` prompt symbol

File: README.md [hunk 3]
```diff
@@ -363,44 +363,69 @@ Topic information: Topic: /chatter | Type: std_msgs/String | Count: 9 | Serializ
...
 If a second value is supplied, it specifies the storage implementation of the bag.
-If no storage implementation is specified, Rosbag2 will try to determine it automatically from the bag.
+If no storage implementation is specified, Rosbag2 will try to determine it automatically from
+the bag.
+
+Alternatively, you can provide input bags via a YAML configuration file using `--input-options`:
+
+```shell dollar
+ros2 bag convert --input-options input_options.yaml --output-options output_options.yaml
+```
```
Comment (christophebedard) [inline README.md]: minor: `shell dollar` doesn't do anything here. The other command examples just use a `$` prompt symbol

File: rosbag2_py/src/rosbag2_py/_transport.cpp [hunk 4]
```diff
@@ -825,11 +826,58 @@ rosbag2_transport::RecordOptions bag_rewrite_default_record_options()
...
+      if (storage_options.uri.empty()) {
+        throw std::runtime_error("Input bag StorageOptions must specify a non-empty 'uri'.");
+      }
+      if (!std::filesystem::exists(storage_options.uri)) {
+        throw std::runtime_error("Bag path '" + storage_options.uri + "' does not exist!");
+      }
+
+      effective_input_options.push_back(storage_options);
+    }
+  }
```
Comment (christophebedard) [inline rosbag2_py/src/rosbag2_py/_transport.cpp:878]: minor, just a thought: extracting this to a separate function would be nice

File: rosbag2_py/src/rosbag2_py/_transport.cpp [hunk 5]
```diff
@@ -1319,5 +1367,33 @@ PYBIND11_MODULE(_transport, m) {
...
+        output_config_file (str):
+          Path to a YAML config file that defines `output_bags` with StorageOptions and
+          RecordOptions.
+
+      Raises:
+        RuntimeError:
+          \- If neither or both input sources are provided.
+          \- If required YAML keys are missing or misformatted.
+          \- If any input bag URI does not exist.
+    )pbdoc"
```
Comment (christophebedard) [inline rosbag2_py/src/rosbag2_py/_transport.cpp:1397]: Are the backslashes before dashes ( `\-`) necessary? Because they're printed as-is:

```
$ python3
>>> import rosbag2_py
>>> help(rosbag2_py.bag_rewrite)

Help on built-in function bag_rewrite in module rosbag2_py._transport:

bag_rewrite(...) method of builtins.PyCapsule instance
    bag_rewrite(input_options: List[rosbag2_py._storage.StorageOptions], input_config_file: str, output_config_file: str) -> None


    Rewrite one or more input bags into one or more output bags according to provided settings.

    Exactly one input source must be provided:
      \- Either `input_options`: a list of StorageOptions describing input bags.
      \- Or `input_config_file`: path to a YAML config file containing `input_bags` entries.

    The `output_config_file` must be a YAML config with an `output_bags` list, where each entry
    may contain StorageOptions and RecordOptions fields used to configure the output bags.

    Args:
      input_options (List[StorageOptions], optional):
        In\-memory input bag configurations. Default is an empty list.
      input_config_file (str, optional):
        Path to a YAML config file that defines `input_bags`. Default is empty.
      output_config_file (str):
        Path to a YAML config file that defines `output_bags` with StorageOptions and
        RecordOptions.

    Raises:
      RuntimeError:
        \- If neither or both input sources are provided.
        \- If required YAML keys are missing or misformatted.
        \- If any input bag URI does not exist.
```

**Review by christophebedard — COMMENTED** [review]
minor comments/suggestions!

File: README.md (hunk 2 above)
Comment (MichaelOrlov) [reply README.md]: Replaced to "```bash"

File: README.md (hunk 3 above)
Comment (MichaelOrlov) [reply README.md]: Replaced to "```bash"

File: rosbag2_py/src/rosbag2_py/_transport.cpp (hunk 5 above)
Comment (MichaelOrlov) [reply rosbag2_py/src/rosbag2_py/_transport.cpp:1397]: Ahh, sorry, I forgot to remove these backslashes after AI generated comments.  
I've removed it now.

File: rosbag2_py/src/rosbag2_py/_transport.cpp (hunk 4 above)
Comment (MichaelOrlov) [reply rosbag2_py/src/rosbag2_py/_transport.cpp:878]: I don't think it makes sense to extract this chunk of code to a separate function. It will be specific just for this place and can't be reused anywhere else.  
There is not much code there, and I would prefer to have it in place for better readability and visibility of what is going on in this function.

**Review by christophebedard — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2325
Gist: https://gist.githubusercontent.com/MichaelOrlov/ae106263983b1941527fea72d449a308/raw/e07f50f934c87a0c9b8cb2f994325ae641a0276a/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py rosbag2_transport rosbag2_storage
TEST args:  --packages-above ros2bag rosbag2_py rosbag2_transport rosbag2_storage
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18144
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/27596/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20661/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/7475/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26617/)

**Comment by MichaelOrlov** [comment]
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18158
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/27613/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20675/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/7489/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26632/)
