### PR TITLE
Address flakiness in the "rosbag2_transport::test_record_services" tests

### LINKED ISSUE #2367: The `rosbag2_transport::test_record_services` tests is tend to be flaky
From CI runs at Apex.AI, it was found that `rosbag2/rosbag2_transport/test:test_record_services` test is tends to be flaky.
Sometimes the tests fail with messages like
```bash
test_record_services.cpp:433 Value of: successful_service_request\<IsPaused\>(cli_is_paused\_, is_paused_response) Actual: false (Service call timed out) Expected: true
```
more detailed log
```shell
2025-12-09T05:32:47.201884Z 01O [ RUN      ] RecordSrvsTest.pause_resume
2025-12-09T05:32:47.201891Z 01O stdin is not a terminal device. Keyboard handling disabled.[INFO] [1765258352.526857450] [rosbag2_recorder_for_test_srvs]: Event publisher thread: Started
2025-12-09T05:32:47.201897Z 01O [INFO] [1765258352.527016204] [rosbag2_recorder_for_test_srvs]: Press SPACE for pausing/resuming
2025-12-09T05:32:47.201903Z 01O [INFO] [1765258352.557148233] [rosbag2_recorder_for_test_srvs]: Starting recording to 'uri'
2025-12-09T05:32:47.201911Z 01O [WARN] [1765258352.559632521] [rosbag2_recorder_for_test_srvs]: No input serialization format specified, using default rmw serialization format: 'cdr'.
2025-12-09T05:32:47.201916Z 01O [INFO] [1765258352.561884139] [rosbag2_recorder_for_test_srvs]: Listening for topics...
2025-12-09T05:32:47.201921Z 01O [INFO] [1765258352.562340174] [rosbag2_recorder_for_test_srvs]: Topics discovery started.
2025-12-09T05:32:47.201929Z 01O [INFO] [1765258352.563296114] [rosbag2_recorder_for_test_srvs]: Recording...
2025-12-09T05:32:47.201934Z 01O [INFO] [1765258352.680825910] [rosbag2_recorder_for_test_srvs]: Subscribed to topic '/recorder_srvs_test_topic'
2025-12-09T05:32:47.201940Z 01O [INFO] [1765258352.685749574] [rosbag2_recorder_for_test_srvs]: All requested topics are subscribed. Stopping discovery...
2025-12-09T05:32:47.201949Z 01O [INFO] [1765258352.686098441] [rosbag2_recorder_for_test_srvs]: Topics discovery stopped.
2025-12-09T05:32:47.201957Z 01O [INFO] [1765258353.283671781] [rosbag2_recorder_for_test_srvs]: Pausing recording.
2025-12-09T05:32:47.201971Z 01O grace/recording/rosbag2/rosbag2_transport/test/rosbag2_transport/test_record_services.cpp:433: Failure
2025-12-09T05:32:47.201976Z 01O Value of: successful_service_request<IsPaused>(cli_is_paused_, is_paused_response)
2025-12-09T05:32:47.201983Z 01O   Actual: false (Service call timed out)
2025-12-09T05:32:47.201986Z 01O Expected: true
2025-12-09T05:32:47.201993Z 01O grace/recording/rosbag2/rosbag2_transport/test/rosbag2_transport/test_record_services.cpp:434: Failure
2025-12-09T05:32:47.202002Z 01O Value of: is_paused_response->paused
2025-12-09T05:32:47.202005Z 01O   Actual: false
2025-12-09T05:32:47.202009Z 01O Expected: true
2025-12-09T05:32:47.202020Z 01O [INFO] [1765258355.387616679] [rosbag2_recorder_for_test_srvs]: Pausing recording.
2025-12-09T05:32:47.202024Z 01O [INFO] [1765258355.387652544] [rosbag2_recorder_for_test_srvs]: Recording stopped
```

### PR DESCRIPTION
**Pull request by MichaelOrlov**
## Description
The `rosbag2_transport::test_record_services` is known to be flaky on CI run.
Please refer to the RCA in the relevant issue https://github.com/ros2/rosbag2/issues/2367#issuecomment-4057689265

Short description of changes:
1. Increase the default service_call_timeout_  to 10 seconds.
2. Use recommended `exec->spin_until_future_complete()` API in the `successful_service_request()` implementation using temporary created executor. Note: we can't reuse `exec_` because `spin_until_future_complete()` requires that the node shall not already be spinning.
3. Removed `client_node_` from adding to the "main" `exec_` executor.

- Fixes #2367

### Is this user-facing behavior change?
No.

### Did you use Generative AI?
Yes. Codex 5.4

### Additional Information
Can be backported.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2368
Gist: https://gist.githubusercontent.com/MichaelOrlov/af651effed135db888c159e24eb39309/raw/2123877217976664b17020526ce9111e3aa6108b/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport
TEST args:  --packages-above rosbag2_transport
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18466
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/28020/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/21000/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/7879/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26971/)

File: rosbag2_transport/test/rosbag2_transport/test_record_services.cpp [hunk 1]
```diff
@@ -189,13 +188,28 @@ class RecordSrvsTest : public RecordIntegrationTestFixture
...
+        return ::testing::AssertionFailure() << "Service call timed out";
+      } else if (ret == rclcpp::FutureReturnCode::INTERRUPTED) {
+        return ::testing::AssertionFailure() << "Service call interrupted";
+      }
+      return ::testing::AssertionFailure() << "Service call failed with unknown error";
     }
+
     if (!future.valid()) {
       return ::testing::AssertionFailure() << "Service call returned invalid future";
     }
```
Comment (fujitatomoya) [inline rosbag2_transport/test/rosbag2_transport/test_record_services.cpp:211]: At that point the future is guaranteed to be ready (the executor only returns SUCCESS when the future completes), so `valid()` check in this if statement should always be true?

**Review by christophebedard — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI.

File: rosbag2_transport/test/rosbag2_transport/test_record_services.cpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_transport/test/rosbag2_transport/test_record_services.cpp:211]: I would keep this check as a defensive programming.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted
