### PR TITLE
[Humble] Add topics with zero message counts to the SQLiteStorage::get_metadata().

### LINKED ISSUE #1719: Ros bag reindex failed to generate topic inside metadata.yaml if the message_count is 0
## Description
On re-indexing a sqllite3 rosbag which originally contains a topic with 0 data inside (message_count:0), the metadata.yaml is not generated properly. The full topic is absent. 

This bug was discovered using the python Teranis rosbags reader's library.  (Confer https://gitlab.com/ternaris/rosbags/-/issues/91). 

### Expected Behavior
The reindex rosbag 's metadata.yaml file shall contains the topic with message_count:0
eg:

```
    - topic_metadata:
        name: /tract/control_signals
        type:msgs/msg/ControlSignal
        serialization_format: cdr
        offered_qos_profiles: "- history: 3\n  depth: 0\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 9223372036\n    nsec: 854775807\n  lifespan:\n    sec: 9223372036\n    nsec: 854775807\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 9223372036\n    nsec: 854775807\n  avoid_ros_namespace_conventions: false"
      message_count: 0  

```

### Actual Behavior
Actually, the full topic section is not present after re-index.

## To Reproduce
1) Take a sqlite bag with at least a topic which has a message_count at 0. 
2) Remove the metadata.yaml 
3) Launch the command
`ros2 bag reindex -s sqlite3  mybag
`
4) Check the generated metadata.yaml, all topics with 0 message count have disappeared. 

PS: This permit to re-generate the problem. In the true world, it shall permit to generate the metadata.yaml in case it has not been generated (which happens several time a day in my case.) 

## System (please complete the following information)
 - OS: [e.g. Ubuntu 22.04]
 - ROS 2 Distro: [Humble]
 - Install Method: [APT, release ]
 - Version: ros-humble-ros2bag                                0.15.9-1jammy.20240217.104352           amd6
 
## Additional context
If we place back from the original data to the re-indexed one the topic section, the python Teranis rosbags reader's library read the file properly. If not it failed. We conclude that the information shall be present inside the db3 but not reported in metadata.yaml.

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Closes https://github.com/ros2/rosbag2/issues/1719
- Analog and manual backport of the #1725. 
Have to do manual backporting because the code base is very different on humble branch in the affected places.

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@MichaelOrlov i am trying to address for `rolling` with https://github.com/ros2/rosbag2/pull/1725.

can i borrow your code for testing? i am not sure if this works for `rolling`... any suggestions?

**Comment by MichaelOrlov** [comment]
@fujitatomoya Sure, feel free to take any parts for rolling. The test should work for rolling as well; however, it will be better to parametrize it to run it for the `mcap` storage as well.

**Comment by MichaelOrlov** [comment]
@fujitatomoya I've updated `get_metadata_include_topics_with_zero_messages` test to run it for mcap as well.
Feel free to take it for rolling. It should fit for rolling as is now. I assume that no modification needed.

File: rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp [hunk 1]
```diff
@@ -463,13 +463,25 @@ void SqliteStorage::prepare_for_reading()
...
+    }
+  } else {
+    auto statement = database_->prepare_statement(
+      "SELECT name, type, serialization_format FROM topics ORDER BY id;");
+    auto query_results = statement->execute_query<std::string, std::string, std::string>();
+
+    for (auto result : query_results) {
+      all_topics_and_types_.push_back(
+        {std::get<0>(result), std::get<1>(result), std::get<2>(result), ""});
+    }
```
Comment (MichaelOrlov) [inline rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp:485]: Note for reviewers. This if-else statement was missing on humble because we didn't backport https://github.com/ros2/rosbag2/pull/1722. However, it is required to correctly fill topics and types map with `offered_qos_profiles`.

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI.

@MichaelOrlov thanks for the note. btw, this is also gonna go to `iron` after this humble fix, right? because https://github.com/ros2/rosbag2/pull/1725 only addressed rolling and jazzy.

**Comment by MichaelOrlov** [comment]
@fujitatomoya Thanks for the review. We can propagate either this PR to the Iron or #1725. Need to double-check the base sources on Iron to see which one is better fit.

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#1722
Gist: https://gist.githubusercontent.com/MichaelOrlov/1a1a4f8ac0ad7670f8603b60e4eef957/raw/40ce70e63ea8ce5ccc15d405be9bd9194282d1d4/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_cpp rosbag2_storage_default_plugins rosbag2_tests
TEST args:  --packages-above rosbag2_cpp rosbag2_storage_default_plugins rosbag2_tests
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14288
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21537/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15821/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1032/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22254/)

**Comment by MichaelOrlov** [comment]
The RHEL9 build fails with error message
```
--- stderr: rosbag2_storage_default_plugins
14:30:34 [K/home/jenkins-agent/workspace/ci_linux-rhel/ws/src/ros2/rosbag2/rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.c[K In member functio[Kvirtual rosbag2_storage::BagMetadata rosbag2_storage_plugins::SqliteStorage::get_metadat[K’:
14:30:34 [K/home/jenkins-agent/workspace/ci_linux-rhel/ws/src/ros2/rosbag2/rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp:539:[Kerro[Kfind[K’ is not a member o[K[K’; did you mea[Kf[K’?
14:30:34   539 |       auto it = std::[Kfind[K(
14:30:34       |                      [K^~~~[K
14:30:34       |                      [Kf[K
```
@clalancette Do you have any idea what RHEL complaining about?

**Comment by MichaelOrlov** [comment]
Re-run RHEL CI job after attempt to fix a build error.
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1041/)

**Comment by MichaelOrlov** [comment]
@clalancette I've fixed the RHEL build. I would appreciate if you would approve this backporting PR additionally so I can merge it.

**Comment by clalancette** [comment]
> @clalancette I've fixed the RHEL build. I would appreciate if you would approve this backporting PR additionally so I can merge it.

So unfortunately, that succeeding build on Humble is for RHEL-9, not RHEL-8 (which is what Humble supports).  I think you should re-run the job on RHEL-8, and see what happens.

**Comment by MichaelOrlov** [comment]
Run CI for RHEL**8**
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1049/)

**Comment by MichaelOrlov** [comment]
The warning message 
```
Failed
rosbag2_py.flake8.E402 (./test/test_convert.py:30:1)

Failing for the past 1 build (Since [#1049](https://ci.ros2.org/job/ci_linux-rhel/1049/) )
Error Message
module level import not at top of file:
from rosbag2_py import (
```
is unrelated to the changes in this PR.
However, I've made a rebase and added suppression for those warning.

Re-run CI for RHEL**8** after the rebase and suppressing PEP8:E402 warning
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1050/)

**Comment by MichaelOrlov** [comment]
@clalancette Ok. Now the RHEL**8** CI job is green. Ready to be approved.

**Review by clalancette — APPROVED** [review]

**Comment by fujitatomoya** [comment]
either @clalancette or @MichaelOrlov can you create the backport PR by mergifyio? (i do not have permission on this repo)

**Comment by clalancette** [comment]
> either @clalancette or @MichaelOrlov can you create the backport PR by mergifyio? (i do not have permission on this repo)

I'm not sure what you mean; this one was the backport PR, no?

**Comment by fujitatomoya** [comment]
@clalancette sorry for the complication,

- rolling, https://github.com/ros2/rosbag2/pull/1725
- jazzy, https://github.com/ros2/rosbag2/pull/1731 (backport of rolling)
- iron, missing
- this PR is for humble

i have consulted with @MichaelOrlov before, because of the base code difference, we did take the different pathes to `rolling/jazzy` and `humble/iron`. so that plan was to develop `humble` with this one and backport to `iron` which is missing now.

**Comment by MichaelOrlov** [comment]
@mergifyio backport iron
