### PR TITLE
resolve relative file paths

### LINKED ISSUE #229: relative_file_paths depends on call site
ros version: Eloquent
The `relative_file_paths` field in the yaml file specifies the location of the data file relative to the location of the terminal when `ros2 bag play <file>` is called.

The following should demonstrate the problem:
```
cd ~
ros2 bag record -a -o demo
^C (terminate the recording)
cd Documents
ros2 bag play ~/demo
```
One gets the following error:
```
Could not open 'demo/demo_0.db3' with 'sqlite3'. 
Error: Failed to read from bag: 
File 'demo/demo_0.db3' does not exist!
```
To clarify: Changing the `relative_file_paths` in the yaml file `demo/metadata.yaml` to `../demo/demo_0.db3` would allow you to call `ros2 bag play ~/demo` from any sub-folder of home (like Documents), but not from home itself

I would expect the relative path to be relative to the yaml file instead.

Might be related to issue [#49](https://github.com/ros2/rosbag2/issues/49)

### PR DESCRIPTION
**Pull request by Karsten1987**
fixes #229 

It basically takes the relative file paths and resolves them relativ to the base folder name, essentially the name of the rosbag to be replayed.
If one of these relativ files is actually in an absolute form, it will ignore it.

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

File: rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp [hunk 1]
```diff
@@ -27,6 +27,32 @@ namespace rosbag2_cpp
 {
 namespace readers
 {
+namespace details
+{
+std::vector<std::string> resolve_relative_paths(
+  const std::string & base_folder, std::vector<std::string> relative_files)
+{
+  // TODO(Karsten1987): It's extremely weird that relative files are prefixed with a folder name
+  auto base_path = rcpputils::fs::path(base_folder).parent_path();
```
Comment (Karsten1987) [inline rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:36]: There is something extremely weird that the relativ files are being prefixed with the actual folder name:

```
 ➭ ros2 bag info rosbag2_2020_04_01-10_14_58/
Files: rosbag2_2020_04_01-10_14_58/rosbag2_2020_04_01-10_14_58_0.db3
```

I would actually love to change this as it does not correspond to the actual folder structure. However, I could see this as an annoying breakage where rosbags recorded from a previous distribution can't easily be replayed without modifying the metadata.yaml.

We could then either come up with some sort of deprecation warning, letting the user know to remove the leading folder name manually in the metadata.yaml or have some sort of `#ifdef <= ELOQUENT`

Comment (emersonknapp) [reply rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:36]: Could you switch this logic based on metadata version?

File: rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp [hunk 2]
```diff
@@ -27,6 +27,35 @@ namespace rosbag2_cpp
 {
 namespace readers
 {
+namespace details
+{
+std::vector<std::string> resolve_relative_paths(
+  const std::string & base_folder, std::vector<std::string> relative_files, size_t version = 4)
```
Comment (zmichaels11) [inline rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:33]:
```suggestion
  const std::string & base_folder, const std::vector<std::string>& relative_files, int version = 4)
```
Can `relative_files` be passed by const ref?
`version` is also an `int` in [BagMetadata](https://github.com/ros2/rosbag2/blob/267702b1fa5c334ad29ca0c7c0aa670b5ea243a0/rosbag2_storage/include/rosbag2_storage/bag_metadata.hpp#L36)

File: rosbag2_cpp/test/rosbag2_cpp/test_multifile_reader.cpp [hunk 3]
```diff
@@ -40,75 +42,165 @@ class MultifileReaderTest : public Test
...
 
+  virtual ~MultifileReaderTest() = default;
+
+  virtual rosbag2_storage::BagMetadata get_metadata() const
+  {
+    rosbag2_storage::BagMetadata metadata;
+
+    metadata.relative_file_paths.push_back(relative_path_1_);
+    metadata.relative_file_paths.push_back(relative_path_2_);
+    metadata.relative_file_paths.push_back(absolute_path_1_);
```
Comment (zmichaels11) [inline rosbag2_cpp/test/rosbag2_cpp/test_multifile_reader.cpp:86]:
```suggestion
    metadata.relative_file_paths = {relative_path_1_, relative_path_2_, absolute_path_1_};
```
Unless you think the current way is cleaner.

File: rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp [hunk 4]
```diff
@@ -27,6 +27,35 @@ namespace rosbag2_cpp
...
+{
+  auto base_path = rcpputils::fs::path(base_folder);
+  if (version < 4) {
+    // In older rosbags (version <=3) relative files are prefixed with the rosbag folder name
+    base_path = rcpputils::fs::path(base_folder).parent_path();
+  }
+
+  if (!base_path.exists()) {
+    throw std::invalid_argument("base folder does not exist: " + base_folder);
+  }
```
Comment (zmichaels11) [inline rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:43]:
```suggestion
  rcpputils::require_true(base_path.exists(), "base folder does not exist: " + base_folder);
```

See [rcpputils::require_true](https://github.com/ros2/rcpputils/blob/52f69e4797c0f596551e977546db21bae664b085/include/rcpputils/asserts.hpp#L95)

File: rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp (hunk 2 above)
Comment (Karsten1987) [reply rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:33]: I am passing `relative_files` deliberately by copy as I'll modify the copy and return it. It's a style thing. I can also pass by reference and copy the content in a new vector.

Comment (zmichaels11) [reply rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:33]: That's fine, I just wanted to verify that you intended to pass by copy.

File: rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp [hunk 5]
```diff
@@ -27,6 +27,33 @@ namespace rosbag2_cpp
...
+  auto base_path = rcpputils::fs::path(base_folder);
+  if (version < 4) {
+    // In older rosbags (version <=3) relative files are prefixed with the rosbag folder name
+    base_path = rcpputils::fs::path(base_folder).parent_path();
+  }
+
+  rcpputils::require_true(base_path.exists(), "base folder does not exist: " + base_folder);
+  if (!base_path.is_directory()) {
+    throw std::invalid_argument("base folder has to be a directory: " + base_folder);
+  }
```
Comment (zmichaels11) [inline rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:44]:
```suggestion
  rcpputils::require_true(base_path.is_directory(), "base folder has to be a directory: " + base_folder);
```
I accidentally left this suggestion out of the previous review.

Comment (Karsten1987) [reply rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:44]: I've addressed this locally as well ;-)

**Comment by Karsten1987** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9900/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5517/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8054/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9753/)

**Comment by Karsten1987** [comment]
@emersonknapp I am getting QoS test failures, did I miss something?

```
16:14:56 7: [ RUN      ] RecordIntegrationTestFixture.published_messages_from_multiple_topics_are_recorded
16:14:56 7: [INFO] [1585869296.012310473] [rosbag2_transport]: Listening for topics...
16:14:56 7: [INFO] [1585869296.018655979] [rosbag2_transport]: Subscribed to topic '/string_topic'
16:14:56 7: [WARN] [1585869296.021000346] [rosbag2_transport]: A new publisher for subscribed topic /string_topic was found that is offering a (possibly) incompatible QoS profile. Not changing subscription QoS. Messages from this publisher may not be recorded.
16:14:56 7: [INFO] [1585869296.023990862] [rosbag2_transport]: Subscribed to topic '/array_topic'
16:14:56 7: [INFO] [1585869296.024012022] [rosbag2_transport]: All requested topics are subscribed. Stopping discovery...
16:15:55 2/2 Test #7: test_record ......................***Timeout  60.04 sec
```
and
```
16:13:55 2: [ RUN      ] RecordIntegrationTestFixture.published_messages_from_multiple_topics_are_recorded
16:13:56 2: [INFO] [1585869235.999994675] [rosbag2_transport]: Listening for topics...
16:13:56 2: [INFO] [1585869236.004100034] [rosbag2_transport]: Subscribed to topic '/string_topic'
16:13:56 2: [INFO] [1585869236.005604653] [rosbag2_transport]: Subscribed to topic '/rosout'
16:13:56 2: [INFO] [1585869236.007492335] [rosbag2_transport]: Subscribed to topic '/parameter_events'
16:13:56 2: [INFO] [1585869236.009682717] [rosbag2_transport]: Subscribed to topic '/array_topic'
16:13:56 2: [WARN] [1585869236.013561291] [rosbag2_transport]: A new publisher for subscribed topic /string_topic was found that is offering a (possibly) incompatible QoS profile. Not changing subscription QoS. Messages from this publisher may not be recorded.
16:13:56 2: [WARN] [1585869236.013963259] [rosbag2_transport]: A new publisher for subscribed topic /rosout was found that is offering a (possibly) incompatible QoS profile. Not changing subscription QoS. Messages from this publisher may not be recorded.
16:13:56 2: [WARN] [1585869236.014366566] [rosbag2_transport]: A new publisher for subscribed topic /parameter_events was found that is offering a (possibly) incompatible QoS profile. Not changing subscription QoS. Messages from this publisher may not be recorded.
16:13:56 2: [WARN] [1585869236.015690209] [rosbag2_transport]: A new publisher for subscribed topic /array_topic was found that is offering a (possibly) incompatible QoS profile. Not changing subscription QoS. Messages from this publisher may not be recorded.
16:14:55 1/2 Test #2: test_record_all ..................***Timeout  60.02 sec
```

**Comment by emersonknapp** [comment]
Hmm, it all passed in my actions and CI run before merging, taking a look

**Comment by emersonknapp** [comment]
Well, the branch was behind, but it seemed like it was somehow running my newest code - I rebased and pushed here (not sure if that was the right move but we'll see what happens with the CI run)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9901/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5519/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8055/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9754/)

File: rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp [hunk 6]
```diff
@@ -43,6 +43,12 @@ std::string format_storage_uri(const std::string & base_folder, uint64_t storage
 
   return (rcpputils::fs::path(base_folder) / storage_file_name.str()).string();
 }
+
+std::string strip_parent_path(const std::string & relative_path)
```
Comment (piraka9011) [inline rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp:47]: Can this be `const`?

Comment (emersonknapp) [reply rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp:47]: This isn't a method

**Comment by emersonknapp** [comment]
Feel free to force push back over it, I made it fail the DCO. But i'm interested to see how the CI run does with this version of the branch

File: rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp (hunk 6 above)
Comment (piraka9011) [reply rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp:47]: I guess what I meant is:
```
const std::string strip_parent_path(...) { ... }
```
It looks like a function to me so not sure what you mean by this isn't a method.

**Comment by emersonknapp** [comment]
Ah, I noticed that your CI runs are again using only cyclone, whereas mine build with all three, and i assume just run on one. When I explicitly run
```
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp colcon test --packages-select rosbag2_transport
```
locally now i see the timeouts.

The spurious warnings are definitely a symptom of what we discussed this morning, and the hanging at the end of the test, I'm not exactly sure. I think that we should probably do the following:
* disable the feature for now (not revert the whole PR)
* add an rmw_implementation matrix on our tests so we catch this by default
* fix it on cyclone and re-enable

Sound good? If so, here's a PR https://github.com/ros2/rosbag2/pull/348

File: rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp (hunk 6 above)
Comment (emersonknapp) [reply rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp:47]: A method is a member function of a class - this is just a plain function. I thought you meant

```
std::string strip_parent_path(...) const {...}
```

What would be the point of returning a const string? It's returning by value so the user can declare the result const if they don't want anything changing it.

Comment (Karsten1987) [reply rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp:47]: why would you want to return a `const std::string` here?

**Comment by Karsten1987** [comment]
CI (with Fast-RTPS):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9903/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5520/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8056/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9755/)

I did indeed only use cyclone, because it's just so much faster to compile without any additional typesupport.

**Comment by Karsten1987** [comment]
Aaaaand once more:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9904/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5521/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8057/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9756/)

File: rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp (hunk 6 above)
Comment (piraka9011) [reply rosbag2_cpp/src/rosbag2_cpp/writers/sequential_writer.cpp:47]: That answers my question, I was wondering if it was necessary or not.
Thanks @emersonknapp

**Comment by emersonknapp** [comment]
Ok @Karsten1987 you should be unblocked by the QoS tests on this one now, that feature is disabled, I am now looking into making it succeed on Cyclone

**Comment by Karsten1987** [comment]
thanks. I have to give some more love to the Windows build.

**Comment by Karsten1987** [comment]
rebase and another try for windows:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9923/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5533/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8071/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9768/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9926/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5536/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8074/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9772/)

**Comment by Karsten1987** [comment]
again after rebasing:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9930/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5540/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8078/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9777/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9931/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5541/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8079/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9779/)

**Comment by Karsten1987** [comment]
I am going slightly crazy with windows and file paths. 
If that doesn't work now, I'll go ahead and disable that weird `ctrl-c` workaround for all tests on windows and address them in https://github.com/ros2/rosbag2/issues/271

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9933/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5543/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8081/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9782/)

**Comment by piraka9011** [comment]
@Karsten1987 I'd recommend just adding DCO and moving forward since we have it on our backlog to resolve the ctrl-c issue.

I've already added some Python tests based on launch in #347 and plan to expand from there to resolve the Windows ctrl-c issue.

**Comment by Karsten1987** [comment]
The last one indeed did it though:
[Build Status](https://ci.ros2.org/job/ci_windows/9785/) // only the regular test failures.

File: rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp [hunk 7]
```diff
@@ -27,6 +28,33 @@ namespace rosbag2_cpp
...
 {
+namespace details
+{
+std::vector<std::string> resolve_relative_paths(
+  const std::string & base_folder, std::vector<std::string> relative_files, const int version = 4)
+{
+  auto base_path = rcpputils::fs::path(base_folder);
+  if (version < 4) {
+    // In older rosbags (version <=3) relative files are prefixed with the rosbag folder name
+    base_path = rcpputils::fs::path(base_folder).parent_path();
```
Comment (jacobperron) [inline rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:39]: If we try to play the bag from the same directory level as the bag directory, then `base_path` is empty and the assertion at L42 fails.

I think this is a bug in rcpputils though, since a path to the current directory should "exist", hopefully.

Comment (jacobperron) [reply rosbag2_cpp/src/rosbag2_cpp/readers/sequential_reader.cpp:39]: Proposed fix in https://github.com/ros2/rcpputils/pull/73
