### PR TITLE
Fix decoder and encode mismatch fails YAML deserialization.

### LINKED ISSUE #2273: RecordOptions fails to deserialize YAML in large-scale topics/services scenarios
## Description
When the topics and services in rosbag2_transport::RecordOptions contain a large number of elements and topic_qos_profile_overrides is not set, performing the YAML encode → decode process throws an exception during deserialization. Consequently, the serialization and deserialization loop cannot complete properly under valid configurations.

### Expected Behavior
For valid RecordOptions, the YAML serialization and deserialization should work properly even when the number of topics/services is large.

### Actual Behavior
Failed to serialize loop

### Test Case
```cpp
#include <gmock/gmock.h>
#include <string>
#include "rosbag2_transport/record_options.hpp"
using namespace ::testing;  // NOLINT

TEST(record_options, test)
{
  rosbag2_transport::RecordOptions options;
  options.topics = std::vector<std::string>(100000, "test_topic"); 
  options.services = std::vector<std::string>(100000, "test_service");

  ASSERT_NO_THROW({
    auto node = YAML::convert<rosbag2_transport::RecordOptions>().encode(options);
    std::stringstream serializer;
    serializer << node;
    auto recreated_node = YAML::Load(serializer.str()).as<rosbag2_transport::RecordOptions>();
    ASSERT_EQ(options.topics, recreated_node.topics);
    ASSERT_EQ(options.services, recreated_node.services);
  });
}
```

### Output
```markdown
[ RUN      ] record_options.test
/home/shangzh/rosbag2_ws/rosbag2/rosbag2_transport/test/rosbag2_transport/test_record_options.cpp:12: Failure
Expected: { auto node = YAML::convert<rosbag2_transport::RecordOptions>().encode(options); std::stringstream serializer; serializer << node; auto recreated_node = YAML::Load(serializer.str()).as<rosbag2_transport::RecordOptions>(); switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("options.topics", "recreated_node.topics", options.topics, recreated_node.topics))) ; else return ::testing::internal::AssertHelper(::testing::TestPartResult::kFatalFailure, "/home/shangzh/rosbag2_ws/rosbag2/rosbag2_transport/test/rosbag2_transport/test_record_options.cpp", 17, gtest_ar.failure_message()) = ::testing::Message(); switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("options.services", "recreated_node.services", options.services, recreated_node.services))) ; else return ::testing::internal::AssertHelper(::testing::TestPartResult::kFatalFailure, "/home/shangzh/rosbag2_ws/rosbag2/rosbag2_transport/test/rosbag2_transport/test_record_options.cpp", 18, gtest_ar.failure_message()) = ::testing::Message(); } doesn't throw an exception.
  Actual: it throws YAML::TypedBadConversion<std::unordered_map<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char> >,rclcpp::QoS,std::hash<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char> > const,rclcpp::QoS> > > > with description "yaml-cpp: error at line 200026, column 3: bad conversion".

[  FAILED  ] record_options.test (2338 ms)
[----------] 1 test from record_options (2338 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2338 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] record_options.test

 1 FAILED TEST
```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

- Fixes #2273

### CODE REVIEW

File: rosbag2_storage/src/rosbag2_storage/qos.cpp [hunk 1]
```diff
@@ -277,7 +277,7 @@ bool convert<std::vector<rclcpp::QoS>>::decode(
 Node convert<std::unordered_map<std::string, rclcpp::QoS>>::encode(
   const std::unordered_map<std::string, rclcpp::QoS> & rhs)
 {
-  Node node{NodeType::Sequence};
+  Node node{NodeType::Map};
```
Comment (fujitatomoya) [inline rosbag2_storage/src/rosbag2_storage/qos.cpp]: The encoder was creating a NodeType::Sequence but the decoder expected a NodeType::Map.
This mismatch caused YAML deserialization to fail, especially noticeable with large test data.

**Review by fujitatomoya — COMMENTED** [review]
@MichaelOrlov i think this is bug, can you take a look?

File: rosbag2_storage/src/rosbag2_storage/qos.cpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_storage/src/rosbag2_storage/qos.cpp]: Well, the original fields in the `rosbag2_transport::RecordOptions` are C++ vectors.
IMO, the node type sequence is a better fit for the C++ alternative.  
I think it would be more appropriate to fix it on the decoder side to use a sequence as well.

Comment (fujitatomoya) [reply rosbag2_storage/src/rosbag2_storage/qos.cpp]: that is surely something we can do. it is either encoder to `Map` or decoder to `Sequence`. the reason that i wanted to change the encoder is encoder changes are forward-only, backward compatibility is paramount for decoders. this is usually avoided in data streaming framework... but your proposal also make rational sense.

Comment (fujitatomoya) [reply rosbag2_storage/src/rosbag2_storage/qos.cpp]: https://github.com/ros2/rosbag2/pull/2277/changes/043b636ee04a7e77978a48f225fa42e9e943d343

**Comment by fujitatomoya** [comment]
Pulls: ros2/rosbag2#2277
Gist: https://gist.githubusercontent.com/fujitatomoya/addf2afc96821e5acfe9d2be10d60de2/raw/7296d77595223b78df34b2bb0219db361f088fd5/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport rosbag2_storage
TEST args:  --packages-above rosbag2_transport rosbag2_storage
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17852
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26719/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20351/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6519/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26310/)

File: rosbag2_storage/src/rosbag2_storage/qos.cpp [hunk 2]
```diff
@@ -279,27 +279,42 @@ Node convert<std::unordered_map<std::string, rclcpp::QoS>>::encode(
...
 bool convert<std::unordered_map<std::string, rclcpp::QoS>>::decode(
   const Node & node, std::unordered_map<std::string, rclcpp::QoS> & rhs, int version)
 {
-  if (!node.IsMap()) {
+  rhs.clear();
+
+  if (node.IsSequence()) {
+    // New sequence format
+    for (const auto & element : node) {
+      std::string topic = element["topic"].as<std::string>();
```
Comment (MichaelOrlov) [inline rosbag2_storage/src/rosbag2_storage/qos.cpp:298]: Minor, nitpick (could be merged without it):
```suggestion
      std::string topic_name = element["topic"].as<std::string>();
```

**Review by MichaelOrlov — APPROVED** [review]
LGTM.

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26778/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20358/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6527/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26317/)

**Comment by fujitatomoya** [comment]
@Mergifyio backport jazzy kilted
