### PR TITLE
minor error checks for rosbag2_cpp

### LINKED ISSUE #2119: SequentialWriter::write() lacks null pointer check, causing crash
## Description
The function rosbag2_cpp::writers::SequentialWriter::write() dereferences the input pointer without checking if it is null, causing crash.

### Expected Behavior
no crash

### Actual Behavior
crash

### Test Case
```cpp
#include <gmock/gmock.h>
#include <filesystem>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "mock_converter.hpp"
#include "mock_converter_factory.hpp"
#include "mock_metadata_io.hpp"
#include "mock_storage.hpp"
#include "mock_storage_factory.hpp"
#include "rmw/rmw.h"
#include "rclcpp/serialization.hpp"
#include "rclcpp/serialized_message.hpp"
#include "rosbag2_cpp/rmw_implemented_serialization_format_converter.hpp"
#include "rosbag2_cpp/writers/sequential_writer.hpp"
#include "rosbag2_cpp/writer.hpp"
#include "rosbag2_storage/ros_helper.hpp"
#include "std_msgs/msg/string.hpp"
using namespace testing;  // NOLINT
namespace fs = std::filesystem;

class SerializationConverterTest : public Test {
public:
  SerializationConverterTest() {
    storage_factory_ = std::make_unique<StrictMock<MockStorageFactory>>();
    storage_ = std::make_shared<NiceMock<MockStorage>>();
    converter_factory_ = std::make_shared<StrictMock<MockConverterFactory>>();
    metadata_io_ = std::make_unique<NiceMock<MockMetadataIo>>();
    tmp_dir_path_ = fs::temp_directory_path() / "SerializationConverterTest";
    storage_options_ = rosbag2_storage::StorageOptions{};
    storage_options_.uri = (tmp_dir_path_ / bag_base_dir_).string();
    fs::remove_all(tmp_dir_path_);
    ON_CALL(*storage_factory_, open_read_write(_)).WillByDefault(
      DoAll(
        Invoke(
          [this](const rosbag2_storage::StorageOptions & storage_options) {
            mock_storage_data_.clear();
            (void)storage_options;
          }),
        Return(storage_)));
    EXPECT_CALL(*storage_factory_, open_read_write(_)).Times(AtLeast(1));
    ON_CALL(*storage_, set_read_order).WillByDefault(Return(true));
    ON_CALL(
      *storage_,
      write(An<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>>())).WillByDefault(
      [this](std::shared_ptr<const rosbag2_storage::SerializedBagMessage> serialized_message) {
        mock_storage_data_.push_back(serialized_message);
      });
    EXPECT_CALL(*storage_, write(An<const std::vector<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>> &>())).Times(0);
    EXPECT_CALL(*storage_, get_bagfile_size()).Times(0);
  }

  ~SerializationConverterTest() override {
    fs::remove_all(tmp_dir_path_);
  }

  std::shared_ptr<rosbag2_storage::SerializedBagMessage> make_test_msg() {
    std_msgs::msg::String std_string_msg;
    std_string_msg.data = test_msg_content_;
    auto rclcpp_serialized_msg = std::make_shared<rclcpp::SerializedMessage>();
    rclcpp::Serialization<std_msgs::msg::String> serialization;
    serialization.serialize_message(&std_string_msg, rclcpp_serialized_msg.get());
    auto message = std::make_shared<rosbag2_storage::SerializedBagMessage>();
    message->topic_name = test_topic_name_;
    message->serialized_data = rosbag2_storage::make_serialized_message(
      rclcpp_serialized_msg->get_rcl_serialized_message().buffer, rclcpp_serialized_msg->size());
    return message;
  }

  std::unique_ptr<StrictMock<MockStorageFactory>> storage_factory_;
  std::shared_ptr<NiceMock<MockStorage>> storage_;
  std::shared_ptr<StrictMock<MockConverterFactory>> converter_factory_;
  std::unique_ptr<MockMetadataIo> metadata_io_;
  fs::path tmp_dir_path_;
  const std::string bag_base_dir_ = "test_bag";
  const std::string test_msg_content_ = "Test message string";
  const std::string test_topic_name_ = "test_topic";
  rosbag2_storage::StorageOptions storage_options_;
  std::vector<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>> mock_storage_data_;
  std::unique_ptr<rosbag2_cpp::Writer> writer_;
};

TEST_F(SerializationConverterTest, test1) {
  auto sequential_writer = std::make_unique<rosbag2_cpp::writers::SequentialWriter>(
    std::move(storage_factory_), converter_factory_, std::move(metadata_io_));
  writer_ = std::make_unique<rosbag2_cpp::Writer>(std::move(sequential_writer));
  const std::string mock_serialization_format = "mock_serialization_format";
  const std::string rmw_serialization_format = rmw_get_serialization_format();
  auto mock_converter = std::make_unique<StrictMock<MockConverter>>();
  std::vector<std::shared_ptr<const rosbag2_cpp::rosbag2_introspection_message_t>>
    intercepted_converter_messages;
  
  EXPECT_CALL(
    *mock_converter,
    serialize(
      An<std::shared_ptr<const rosbag2_cpp::rosbag2_introspection_message_t>>(),
      An<const rosidl_message_type_support_t *>(),
      An<std::shared_ptr<rosbag2_storage::SerializedBagMessage>>())).
  WillRepeatedly(
    [&](std::shared_ptr<const rosbag2_cpp::rosbag2_introspection_message_t> ros_message,
    const rosidl_message_type_support_t * type_support,
    std::shared_ptr<rosbag2_storage::SerializedBagMessage> serialized_message) {
      intercepted_converter_messages.push_back(ros_message);
      (void)serialized_message;
      (void)type_support;
    });

  auto rmw_converter =
    std::make_unique<rosbag2_cpp::RMWImplementedConverter>(rmw_serialization_format);
  
  EXPECT_CALL(*converter_factory_, load_serializer(mock_serialization_format))
  .WillOnce(Return(ByMove(std::move(mock_converter))));
  EXPECT_CALL(*converter_factory_, load_deserializer(rmw_serialization_format))
  .WillOnce(Return(ByMove(std::move(rmw_converter))));

  std::shared_ptr<rosbag2_storage::SerializedBagMessage> null_message = nullptr;
  writer_->open(storage_options_, {rmw_serialization_format, mock_serialization_format});
  writer_->create_topic({0u, test_topic_name_, "std_msgs/msg/String", "", {}, ""});
  writer_->write(null_message);
  ASSERT_EQ(intercepted_converter_messages.size(), 0);
}
```

### Output
```markdown
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SerializationConverterTest
[ RUN      ] SerializationConverterTest.test1
AddressSanitizer:DEADLYSIGNAL
=================================================================
==96907==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7def37e38029 bp 0x7ffd38f852b0 sp 0x7ffd38f85090 T0)
==96907==The signal is caused by a READ memory access.
==96907==Hint: address points to the zero page.
    #0 0x7def37e38029 in rosbag2_cpp::writers::SequentialWriter::write(std::shared_ptr<rosbag2_storage::SerializedBagMessage const>) (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x238029) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #1 0x7def37e323e7 in rosbag2_cpp::Writer::write(std::shared_ptr<rosbag2_storage::SerializedBagMessage const>) (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x2323e7) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #2 0x612aa769799e in SerializationConverterTest_test1_Test::TestBody() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x1bb99e) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #3 0x612aa7816ab5 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x33aab5) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #4 0x612aa780442f in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x32842f) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #5 0x612aa77abb05 in testing::Test::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2cfb05) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #6 0x612aa77ad2e1 in testing::TestInfo::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2d12e1) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #7 0x612aa77ae63a in testing::TestSuite::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2d263a) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #8 0x612aa77d5365 in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2f9365) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #9 0x612aa7819f10 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x33df10) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #10 0x612aa78076cc in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x32b6cc) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #11 0x612aa77d196f in testing::UnitTest::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2f596f) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #12 0x612aa777be11 in RUN_ALL_TESTS() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x29fe11) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #13 0x612aa777bd5d in main (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x29fd5d) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)
    #14 0x7def35c2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #15 0x7def35c2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #16 0x612aa7696354 in _start (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x1ba354) (BuildId: 935ab9c54c3061027330b8edb2e60049c7cd1363)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x238029) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f) in rosbag2_cpp::writers::SequentialWriter::write(std::shared_ptr<rosbag2_storage::SerializedBagMessage const>)
==96907==ABORTING
```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### LINKED ISSUE #2125: RMWImplementedConverter::deserialize（） lacks null pointer check, causing crash
## Description
The rosbag2_cpp::RMWImplementedConverter::deserialize function does not check for null pointers in its input parameters, causing crash .

### Expected Behavior
no crash

### Actual Behavior
crash

### Test Case
```cpp
#include <gmock/gmock.h>
#include <filesystem>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "mock_converter.hpp"
#include "mock_converter_factory.hpp"
#include "mock_metadata_io.hpp"
#include "mock_storage.hpp"
#include "mock_storage_factory.hpp"
#include "rmw/rmw.h"
#include "rclcpp/serialization.hpp"
#include "rclcpp/serialized_message.hpp"
#include "rosbag2_cpp/rmw_implemented_serialization_format_converter.hpp"
#include "rosbag2_cpp/writers/sequential_writer.hpp"
#include "rosbag2_cpp/writer.hpp"
#include "rosbag2_storage/ros_helper.hpp"
#include "std_msgs/msg/string.hpp"
using namespace testing;  // NOLINT
namespace fs = std::filesystem;
class SerializationConverterTest : public Test
{
public:
  SerializationConverterTest()
  {
    storage_factory_ = std::make_unique<StrictMock<MockStorageFactory>>();
    storage_ = std::make_shared<NiceMock<MockStorage>>();
    converter_factory_ = std::make_shared<StrictMock<MockConverterFactory>>();
    metadata_io_ = std::make_unique<NiceMock<MockMetadataIo>>();
    tmp_dir_path_ = fs::temp_directory_path() / "SerializationConverterTest";
    storage_options_ = rosbag2_storage::StorageOptions{};
    storage_options_.uri = (tmp_dir_path_ / bag_base_dir_).string();
    fs::remove_all(tmp_dir_path_);
    ON_CALL(*storage_factory_, open_read_write(_)).WillByDefault(
      DoAll(
        Invoke(
          [this](const rosbag2_storage::StorageOptions & storage_options) {
            mock_storage_data_.clear();
            (void)storage_options;
          }),
        Return(storage_)));
    EXPECT_CALL(*storage_factory_, open_read_write(_)).Times(AtLeast(1));
    ON_CALL(*storage_, set_read_order).WillByDefault(Return(true));
    ON_CALL(
      *storage_,
      write(An<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>>())).WillByDefault(
      [this](std::shared_ptr<const rosbag2_storage::SerializedBagMessage> serialized_message) {
        mock_storage_data_.push_back(serialized_message);
      });
    using VectorSharedBagMessages =
      std::vector<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>>;
    EXPECT_CALL(*storage_, write(An<const VectorSharedBagMessages &>())).Times(0);
    EXPECT_CALL(*storage_, get_bagfile_size()).Times(0);
  }
  ~SerializationConverterTest() override
  {
    fs::remove_all(tmp_dir_path_);
  }
  std::shared_ptr<rosbag2_storage::SerializedBagMessage> make_test_msg()
  {
    std_msgs::msg::String std_string_msg;
    std_string_msg.data = test_msg_content_;
    auto rclcpp_serialized_msg = std::make_shared<rclcpp::SerializedMessage>();
    rclcpp::Serialization<std_msgs::msg::String> serialization;
    serialization.serialize_message(&std_string_msg, rclcpp_serialized_msg.get());
    auto message = std::make_shared<rosbag2_storage::SerializedBagMessage>();
    message->topic_name = test_topic_name_;
    message->serialized_data = rosbag2_storage::make_serialized_message(
      rclcpp_serialized_msg->get_rcl_serialized_message().buffer, rclcpp_serialized_msg->size());
    return message;
  }
  std::unique_ptr<StrictMock<MockStorageFactory>> storage_factory_;
  std::shared_ptr<NiceMock<MockStorage>> storage_;
  std::shared_ptr<StrictMock<MockConverterFactory>> converter_factory_;
  std::unique_ptr<MockMetadataIo> metadata_io_;
  fs::path tmp_dir_path_;
  const std::string bag_base_dir_ = "test_bag";
  const std::string test_msg_content_ = "Test message string";
  const std::string test_topic_name_ = "test_topic";
  rosbag2_storage::StorageOptions storage_options_;
  std::vector<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>> mock_storage_data_;
  std::unique_ptr<rosbag2_cpp::Writer> writer_;
};

TEST_F(SerializationConverterTest, test) {
  auto rmw_converter = std::make_unique<rosbag2_cpp::RMWImplementedConverter>(rmw_get_serialization_format());
  auto null_msg = std::shared_ptr<const rosbag2_storage::SerializedBagMessage>();
  EXPECT_THROW({
    try {
      rmw_converter->deserialize(null_msg, nullptr, nullptr);
    } catch (const std::runtime_error& e) {
      EXPECT_STREQ("Cannot deserialize a null message", e.what());
      throw;
    }
  }, std::runtime_error);
}

```

### Output
```markdown
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SerializationConverterTest
[ RUN      ] SerializationConverterTest.test
AddressSanitizer:DEADLYSIGNAL
=================================================================
==99905==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7dbe608030bd bp 0x7ffc904d67e0 sp 0x7ffc904d5f60 T0)
==99905==The signal is caused by a READ memory access.
==99905==Hint: address points to the zero page.
    #0 0x7dbe608030bd in rosbag2_cpp::RMWImplementedConverter::deserialize(std::shared_ptr<rosbag2_storage::SerializedBagMessage const>, rosidl_message_type_support_t const*, std::shared_ptr<rosbag2_cpp::rosbag2_introspection_message_t>) (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x2030bd) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #1 0x6171c820079f in SerializationConverterTest_test_Test::TestBody() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x15c79f) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #2 0x6171c8354437 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2b0437) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #3 0x6171c8341db1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x29ddb1) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #4 0x6171c82e9301 in testing::Test::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x245301) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #5 0x6171c82eaadd in testing::TestInfo::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x246add) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #6 0x6171c82ebe36 in testing::TestSuite::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x247e36) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #7 0x6171c8312b61 in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x26eb61) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #8 0x6171c8357892 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2b3892) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #9 0x6171c834504e in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2a104e) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #10 0x6171c830f16b in testing::UnitTest::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x26b16b) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #11 0x6171c82b960d in RUN_ALL_TESTS() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x21560d) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #12 0x6171c82b9559 in main (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x215559) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)
    #13 0x7dbe5e42a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x7dbe5e42a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0x6171c8200374 in _start (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x15c374) (BuildId: 40d552cc8eb373acbc800b799e6b591c51ea3e1d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x2030bd) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f) in rosbag2_cpp::RMWImplementedConverter::deserialize(std::shared_ptr<rosbag2_storage::SerializedBagMessage const>, rosidl_message_type_support_t const*, std::shared_ptr<rosbag2_cpp::rosbag2_introspection_message_t>)
==99905==ABORTING
```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### LINKED ISSUE #2126: RMWImplementedConverter::serialize() Does Not Check for Null Pointers, Causing Crash
## Description
The RMWImplementedConverter::serialize() function does not check for null pointers in its input parameters, causing crash .

### Expected Behavior
no crash

### Actual Behavior
crash

### Test Case
```cpp
#include <gmock/gmock.h>
#include <filesystem>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "mock_converter.hpp"
#include "mock_converter_factory.hpp"
#include "mock_metadata_io.hpp"
#include "mock_storage.hpp"
#include "mock_storage_factory.hpp"
#include "rmw/rmw.h"
#include "rclcpp/serialization.hpp"
#include "rclcpp/serialized_message.hpp"
#include "rosbag2_cpp/rmw_implemented_serialization_format_converter.hpp"
#include "rosbag2_cpp/writers/sequential_writer.hpp"
#include "rosbag2_cpp/writer.hpp"
#include "rosbag2_storage/ros_helper.hpp"
#include "std_msgs/msg/string.hpp"

using namespace testing;  // NOLINT
namespace fs = std::filesystem;

class SerializationConverterTest : public Test
{
public:
  SerializationConverterTest()
  {
    storage_factory_ = std::make_unique<StrictMock<MockStorageFactory>>();
    storage_ = std::make_shared<NiceMock<MockStorage>>();
    converter_factory_ = std::make_shared<StrictMock<MockConverterFactory>>();
    metadata_io_ = std::make_unique<NiceMock<MockMetadataIo>>();
    tmp_dir_path_ = fs::temp_directory_path() / "SerializationConverterTest";
    storage_options_ = rosbag2_storage::StorageOptions{};
    storage_options_.uri = (tmp_dir_path_ / bag_base_dir_).string();
    fs::remove_all(tmp_dir_path_);
    ON_CALL(*storage_factory_, open_read_write(_)).WillByDefault(
      DoAll(
        Invoke(
          [this](const rosbag2_storage::StorageOptions & storage_options) {
            mock_storage_data_.clear();
            (void)storage_options;
          }),
        Return(storage_)));
    EXPECT_CALL(*storage_factory_, open_read_write(_)).Times(AtLeast(1));
    ON_CALL(*storage_, set_read_order).WillByDefault(Return(true));
    ON_CALL(
      *storage_,
      write(An<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>>())).WillByDefault(
      [this](std::shared_ptr<const rosbag2_storage::SerializedBagMessage> serialized_message) {
        mock_storage_data_.push_back(serialized_message);
      });
    using VectorSharedBagMessages =
      std::vector<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>>;
    EXPECT_CALL(*storage_, write(An<const VectorSharedBagMessages &>())).Times(0);
    EXPECT_CALL(*storage_, get_bagfile_size()).Times(0);
  }

  ~SerializationConverterTest() override
  {
    fs::remove_all(tmp_dir_path_);
  }

  std::shared_ptr<rosbag2_storage::SerializedBagMessage> make_test_msg()
  {
    std_msgs::msg::String std_string_msg;
    std_string_msg.data = test_msg_content_;
    auto rclcpp_serialized_msg = std::make_shared<rclcpp::SerializedMessage>();
    rclcpp::Serialization<std_msgs::msg::String> serialization;
    serialization.serialize_message(&std_string_msg, rclcpp_serialized_msg.get());
    auto message = std::make_shared<rosbag2_storage::SerializedBagMessage>();
    message->topic_name = test_topic_name_;
    message->serialized_data = rosbag2_storage::make_serialized_message(
      rclcpp_serialized_msg->get_rcl_serialized_message().buffer, rclcpp_serialized_msg->size());
    return message;
  }

  std::unique_ptr<StrictMock<MockStorageFactory>> storage_factory_;
  std::shared_ptr<NiceMock<MockStorage>> storage_;
  std::shared_ptr<StrictMock<MockConverterFactory>> converter_factory_;
  std::unique_ptr<MockMetadataIo> metadata_io_;
  fs::path tmp_dir_path_;
  const std::string bag_base_dir_ = "test_bag";
  const std::string test_msg_content_ = "Test message string";
  const std::string test_topic_name_ = "test_topic";
  rosbag2_storage::StorageOptions storage_options_;
  std::vector<std::shared_ptr<const rosbag2_storage::SerializedBagMessage>> mock_storage_data_;
  std::unique_ptr<rosbag2_cpp::Writer> writer_;
};

TEST_F(SerializationConverterTest, test) {
  auto rmw_converter = rosbag2_cpp::RMWImplementedConverter(rmw_get_serialization_format());
  auto serialized_msg = std::make_shared<rosbag2_storage::SerializedBagMessage>();
  EXPECT_ANY_THROW(rmw_converter.serialize(nullptr, nullptr, serialized_msg));
  EXPECT_ANY_THROW(rmw_converter.serialize(nullptr, nullptr, nullptr));
}
```

### Output
```markdown
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SerializationConverterTest
[ RUN      ] SerializationConverterTest.test
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11210==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7e2587403311 bp 0x7ffca009de30 sp 0x7ffca009d5b0 T0)
==11210==The signal is caused by a READ memory access.
==11210==Hint: address points to the zero page.
    #0 0x7e2587403311 in rosbag2_cpp::RMWImplementedConverter::serialize(std::shared_ptr<rosbag2_cpp::rosbag2_introspection_message_t const>, rosidl_message_type_support_t const*, std::shared_ptr<rosbag2_storage::SerializedBagMessage>) (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x203311) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #1 0x639c9738a654 in SerializationConverterTest_test_Test::TestBody() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x15c654) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #2 0x639c974de233 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2b0233) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #3 0x639c974cbac5 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x29dac5) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #4 0x639c97472e35 in testing::Test::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x244e35) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #5 0x639c97474611 in testing::TestInfo::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x246611) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #6 0x639c9747596a in testing::TestSuite::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x24796a) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #7 0x639c9749c695 in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x26e695) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #8 0x639c974e168e in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2b368e) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #9 0x639c974ced62 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x2a0d62) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #10 0x639c97498c9f in testing::UnitTest::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x26ac9f) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #11 0x639c97443141 in RUN_ALL_TESTS() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x215141) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #12 0x639c9744308d in main (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x21508d) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)
    #13 0x7e258522a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x7e258522a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0x639c9738a2f4 in _start (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_serialization_converter+0x15c2f4) (BuildId: 53a045d2b4ee335969a42b4381c80b63f00b05a5)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x203311) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f) in rosbag2_cpp::RMWImplementedConverter::serialize(std::shared_ptr<rosbag2_cpp::rosbag2_introspection_message_t const>, rosidl_message_type_support_t const*, std::shared_ptr<rosbag2_storage::SerializedBagMessage>)
==11210==ABORTING
```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

- Fixes #2119 
- Fixes #2125
- Fixes #2126 

### Is this user-facing behavior change?

No, just adding null check.

### Did you use Generative AI?

No

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
I do not really see the test for those classes, but if there were, i am happy to add those test cases.

**Review by fujitatomoya — COMMENTED** [review]
fix liter error.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rosbag2#2127
Gist: https://gist.githubusercontent.com/fujitatomoya/fcf4bd605683596a29c2f498db95f48d/raw/5d718325f5beaefadf70ac1dce6642d84ad2da76/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_cpp
TEST args:  --packages-above rosbag2_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16695
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24570/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18618/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4027/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25112/)

**Comment by fujitatomoya** [comment]
@MichaelOrlov can you take a look?

File: rosbag2_cpp/src/rosbag2_cpp/rmw_implemented_serialization_format_converter.cpp [hunk 1]
```diff
@@ -122,6 +122,14 @@ void RMWImplementedConverter::deserialize(
...
   std::shared_ptr<rosbag2_cpp::rosbag2_introspection_message_t> introspection_message)
 {
+  if (!serialized_message || !serialized_message->serialized_data) {
+    ROSBAG2_CPP_LOG_ERROR("Serialized message is null.");
+    return;
+  }
+  if (!introspection_message || !introspection_message->message) {
+    ROSBAG2_CPP_LOG_ERROR("Introspection message is null.");
+    return;
+  }
```
Comment (christophebedard) [inline rosbag2_cpp/src/rosbag2_cpp/rmw_implemented_serialization_format_converter.cpp]: I feel like throwing an exception instead of logging an error and not doing anything might be better and lead to fewer weird side effects.

**Review by christophebedard — APPROVED** [review]
Seems reasonable, I just have one minor comment.

File: rosbag2_cpp/src/rosbag2_cpp/rmw_implemented_serialization_format_converter.cpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_cpp/src/rosbag2_cpp/rmw_implemented_serialization_format_converter.cpp]: Well, if input is null, there is nothing to do, and it is okay just to log a error or warning. It could be a valid case for an empty message.
However, if memory for output message hasn't been allocated and we can't write the result of the serialization/deserialization due to that - that is kind of situation which shouldn't happened and we should throw an exception.

**Review by MichaelOrlov — COMMENTED** [review]
@fujitatomoya The relevant unit tests are here 
https://github.com/ros2/rosbag2/blob/53f30e902388683fefbe7833d530918abb6ae099/rosbag2_cpp/test/rosbag2_cpp/test_serialization_converter.cpp#L121-L216

Feel free to add more tests to cover changes there.

**Review by MichaelOrlov — CHANGES_REQUESTED** [review]
@fujitatomoya Can you please throw `std::invalid_argument` exceptions for the cases when memory for the output parameter is not allocated when doing serialize/deserialize operation?

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24593/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18639/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4050/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25134/)

**Review by christophebedard — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@MichaelOrlov can we merge this? maybe backports required too 🤔

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted jazzy
