### PR TITLE
Bugfix for deadlocks in Rosbag2 player when calling stop API

### LINKED ISSUE #2056: Deadlock in the Rosbag2 player running from Python when calling stop via service call
## Description
Deadlock in the Rosbag2 player running from Python when calling stop via service call

### Steps to reproduce:
1. Create a Rosbag2 player via the Python exposed API.
   ```Python
     player = Player(args.log_level)
        try:
            player.play(storage_options, play_options)
        except KeyboardInterrupt:
            pass
   ```
2. Call service request to stop from another terminal or process `ros2 service call /rosbag2_recorder/stop rosbag2_interfaces/Stop`

3. It is expected that `player.play(storage_options, play_options)` from step 1 will exit after some time. However, very often it is a hangout forever.

### Expected Behavior
- It is expected that `player.play(storage_options, play_options)` from step 1 will exit after some time.

### Actual Behavior
The `player.play(storage_options, play_options)` from step 1 very often hangs up forever after calling the stop service call.

## System (please complete the following information)
 - OS: [e.g. Ubuntu 22.04]
 - ROS 2 Distro: Rolling
 - Install Method: build from source
 - Version: https://github.com/ros2/rosbag2/commit/269ca13271f3834b90bc3a17fd3fee76825385a7

## Additional context
** Add any other context about the problem here **

### PR DESCRIPTION
**Pull request by MichaelOrlov**
## Description

This PR fixes potential deadlocks in the Rosbag2 player when running from CLI `ros2 bag play` or from Python API and when trying to stop playback via service call from another process or thread.

Please refer to the https://github.com/ros2/rosbag2/issues/2056#issuecomment-3015973746 for the detailed root cause analysis.

- Fixes #2056

### Is this user-facing behavior change?
No.

### Did you use Generative AI?
Yes. I am using GitHub Copilot, GPT-4.1 in my workflow.

### Additional Information
- This PR doesn't contain API/ABI breaking changes and can be backported.

### CODE REVIEW

File: rosbag2_transport/src/rosbag2_transport/player.cpp [hunk 1]
```diff
@@ -581,17 +585,19 @@ bool PlayerImpl::is_storage_completely_loaded() const
...
-      return false;
-    }
+  rcpputils::unique_lock<std::mutex> is_in_playback_lk(is_in_playback_mutex_);
+  if (is_in_playback_.exchange(true)) {
+    RCLCPP_WARN_STREAM(
+      owner_->get_logger(),
+      "Trying to play() while in playback, dismissing request.");
+    progress_bar_->update(clock_->is_paused() ? PlayerStatus::PAUSED : PlayerStatus::RUNNING);
+    return false;
   }
```
Comment (christophebedard) [inline rosbag2_transport/src/rosbag2_transport/player.cpp:595]: More of a question: The other changes make sense, but I don't think this increase in the lock scope here (from just this scope to the whole method) is required, right? However, this method itself isn't really doing much, so I think it's fine

Comment (MichaelOrlov) [reply rosbag2_transport/src/rosbag2_transport/player.cpp:595]: The lock for the full scope of the `Play()` method is needed to avoid race conditions with `stop()` and `play_next()` methods.  
Before it was possible a situation where we had not completely started `Play()` but had already called `stop()` or `play_next` on halfway through the `Play()` method.

Comment (christophebedard) [reply rosbag2_transport/src/rosbag2_transport/player.cpp:595]: ahh, OK, got it.

**Review by christophebedard — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2057
Gist: https://gist.githubusercontent.com/MichaelOrlov/cd0c5a4f2eeb421377d0a61f53e4b7ea/raw/9cf9826d015e94bc7d5f02729e6458b55e209cf2/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16363
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24150/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18224/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3579/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24759/)

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted jazzy
