### PR TITLE
Address flakiness in rosbag2_play_end_to_end tests

### LINKED ISSUE #408: test_rosbag2_play_end_to_end flaky
## Description
The test regressed overnight. 

https://ci.ros2.org/job/nightly_linux_release/1539/testReport/(root)/projectroot/test_rosbag2_play_end_to_end/

```
-- run_test.py: invoking following command in '/home/jenkins-agent/workspace/nightly_linux_release/ws/build/rosbag2_tests':
 - /home/jenkins-agent/workspace/nightly_linux_release/ws/build/rosbag2_tests/test_rosbag2_play_end_to_end --gtest_output=xml:/home/jenkins-agent/workspace/nightly_linux_release/ws/build/rosbag2_tests/test_results/rosbag2_tests/test_rosbag2_play_end_to_end.gtest.xml
Running main() from gmock_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from PlayEndToEndTestFixture
[ RUN      ] PlayEndToEndTestFixture.play_end_to_end_test
[INFO] [1589203781.466639626] [rosbag2_storage]: Opened database 'cdr_test/cdr_test_0.db3' for READ_ONLY.
[       OK ] PlayEndToEndTestFixture.play_end_to_end_test (612 ms)
[ RUN      ] PlayEndToEndTestFixture.play_fails_gracefully_if_bag_does_not_exist
[       OK ] PlayEndToEndTestFixture.play_fails_gracefully_if_bag_does_not_exist (237 ms)
[ RUN      ] PlayEndToEndTestFixture.play_fails_gracefully_if_needed_coverter_plugin_does_not_exist
[       OK ] PlayEndToEndTestFixture.play_fails_gracefully_if_needed_coverter_plugin_does_not_exist (283 ms)
[ RUN      ] PlayEndToEndTestFixture.play_filters_by_topic
[INFO] [1589203782.518986655] [rosbag2_storage]: Opened database 'cdr_test/cdr_test_0.db3' for READ_ONLY.
[WARN] [1589203782.746890923] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[INFO] [1589203782.999761379] [rosbag2_storage]: Opened database 'cdr_test/cdr_test_0.db3' for READ_ONLY.
```

Looking at the history it has failed 4 out of 7 of the last buils. 

https://ci.ros2.org/job/nightly_linux_release/1539/testReport/(root)/projectroot/test_rosbag2_play_end_to_end/history/

If this cannot be resolved immediately I will plan to add an xfail flag to this to avoid busting CI and this ticket can stay open to track the failure.

This is also failing on arm64 https://ci.ros2.org/job/nightly_linux-aarch64_debug/1202/testReport/
And debug: https://ci.ros2.org/job/nightly_linux_debug/1550/testReport/(root)/projectroot/test_rosbag2_play_end_to_end/

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Closes #408 
Make test_rosbag2_play_end_to_end more deterministic
- Change QoS depth in test databases to correspond number of messages
- Change QoS durability to transient local in test DB and mcap file
- Explicitly specify QoS depth = 10 for subscribers
- Explicitly specify QoS reliability to reliable for subscribers
- Explicitly specify QoS durability to transient local for subscribers
- Update metadata in test DB and mcap files to the latest version(7)
- Start player in pause mode and wait on subscribers for matched
publishers from player then send resume service call to unpause.
- Add spin_and_wait_for_matched(topic_names) for SubscriptionManager
- Remove xfail test_rosbag2_play_end_to_end

Add wait_for_matched for record_end_to_end_exits_gracefully_on_sigterm
- Remove xfail for test_rosbag2_info_end_to_end

Fix for play_filters_by_topic test
- Uncomment play_filters_by_topic test
- Use proper qos settings for subscribers in `play_filters_by_topic`
and fix expectations about number of published messages.
- Log warning if SubscriptionManager::continue_spinning(..) finished by
timeout.
- Enable `play_end_to_end_test` for windows.

Note: **Didn't remove xfail for test_rosbag2_record_end_to_end** because tests fails on Windows build due to absence of the console control handling for  `CTRL_C_EVENT` and `CTRL_SHUTDOWN_EVENT` events.
Will address `test_rosbag2_record_end_to_end` tests in follow up PRs.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/001cdcfa299a0cd40badfb30fae6aa8c/raw/c737f0f4f0068f00fccb96bf909caf35cb4fb722/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_tests
TEST args:  --packages-above rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11915
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18572/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13116/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19309/)

**Comment by MichaelOrlov** [comment]
Re-run CI with `--retest-until-fail 5` after returning `xfail` for `test_rosbag2_record_end_to_end` and enforcing QoS settings for subscribers.
Gist: https://gist.githubusercontent.com/MichaelOrlov/001cdcfa299a0cd40badfb30fae6aa8c/raw/c737f0f4f0068f00fccb96bf909caf35cb4fb722/ros2.repos
BUILD args: --packages-above-and-dependencies rosbag2_tests
TEST args: --packages-above rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12008
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18683/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13209/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19411/)

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by MichaelOrlov** [comment]
Re-run CI with --retest-until-fail 5 after fixing and enabling `play_filters_by_topic` test.
Gist: https://gist.githubusercontent.com/MichaelOrlov/001cdcfa299a0cd40badfb30fae6aa8c/raw/c737f0f4f0068f00fccb96bf909caf35cb4fb722/ros2.repos
BUILD args: --packages-above-and-dependencies rosbag2_test_common rosbag2_tests
TEST args: --packages-above rosbag2_test_common rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12009
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18684/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13210/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19412/)

File: rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp [hunk 1]
```diff
@@ -127,13 +127,56 @@ class SubscriptionManager
...
+
+      matched = true;
+      for (const auto & topic_name : topic_names) {
+        if (subscriptions_.find(topic_name) == subscriptions_.end() ||
+          subscriptions_[topic_name]->get_publisher_count() < n_publishers_to_match)
+        {
+          matched = false;
+          break;
+        }
+      }
```
Comment (clalancette) [inline rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp:167]: Consider the case where `spin_node_some` has no work to do; in that case, it may[1] quickly return, we will quickly run through the loop above, and then we'll go through the outer loop again quickly, burning a lot of CPU.  It is probably worthwhile to add a short sleep here (maybe a millisecond).

[1] Today that isn't too much of an issue, but with some of the executor speedup work this becomes more of a potential problem.

File: rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp [hunk 2]
```diff
@@ -127,13 +127,56 @@ class SubscriptionManager
...
+    const std::vector<std::string> & topic_names,
+    std::chrono::duration<double> timeout = std::chrono::seconds(10),
+    size_t n_publishers_to_match = 1)
+  {
+    // Sanity check that we have valid input
+    if (topic_names.empty()) {
+      throw std::invalid_argument("List of topic names is empty");
+    }
+    for (const auto & topic_name : topic_names) {
+      if (subscriptions_.find(topic_name) == subscriptions_.end()) {
```
Comment (clalancette) [inline rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp]: This is a nitpick, but I find using count to be more readable here.  But feel free to ignore this comment if you like `find` better:

```suggestion
      if (subscriptions_.count(topic_name) == 0) {
```

File: rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp [hunk 3]
```diff
@@ -24,25 +24,45 @@
...
 
+#include "rosbag2_interfaces/srv/resume.hpp"
 #include "rosbag2_test_common/process_execution_helpers.hpp"
 #include "rosbag2_test_common/subscription_manager.hpp"
 #include "rosbag2_test_common/tested_storage_ids.hpp"
 
 #include "test_msgs/msg/arrays.hpp"
 #include "test_msgs/msg/basic_types.hpp"
-#include "test_msgs/message_fixtures.hpp"
+//  #include "test_msgs/message_fixtures.hpp"
```
Comment (clalancette) [inline rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp]: Nit: just remove this commented-out line.

File: rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp [hunk 4]
```diff
@@ -95,8 +151,9 @@ TEST_P(PlayEndToEndTestFixture, play_end_to_end_test) {
         Field(
           &test_msgs::msg::Arrays::string_values,
           ElementsAre("Complex Hello1", "Complex Hello2", "Complex Hello3")))));
+  stop_execution(process_id);
+  cleanup_process_handle.cancel();
```
Comment (clalancette) [inline rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp]: Do we need this at all?  Can't we just let `cleanup_process_handle` go out of scope and do this for us?

(same question a few times below as well)

**Review by clalancette — CHANGES_REQUESTED** [review]
I've left a few pieces of minor feedback.

File: rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp:167]: @clalancette I think it would be better to replace it with `exec.spin_node_once(subscriber_node_, timeout);` instead of adding delay after `spin_node_some`. 
What do you think?

File: rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp (hunk 4 above)
Comment (MichaelOrlov) [reply rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp]: The rationale for calling `stop_execution(process_id);` explicitly is because there are inside of it a bunch or gtest checks which might fail and it would be better to have a clean backtrace where from it fails rather then generic failure from `scope_exit`. When there are only one call for start/stop execution it might be not a big deal and would be obviously that error happened when leaving the test case. But in the case when multiple calls for start/stop execution in one test e.g. `play_filters_by_topic` it might be not obvious to understand in what exact scenario it was failing.

For the sake of consistency and chances that someone will add more start/stop execution calls in the test I decided to keep explicit call for stop.

File: rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp (hunk 3 above)
Comment (MichaelOrlov) [reply rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp]: Fixed

File: rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp:167]: @clalancette I have to admit that my proposal of replacing `spin_node_some` with `spin_node_once` was a bad idea.
It turns out that `spin_node_once` will block up until timeout in the test scenario and test execution time is increasing up to the timeout of 10 seconds for `wait_for_matched();`
I've implemented a fix as you suggested with small sleep for a few milliseconds to avoid busy loop.

File: rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp (hunk 4 above)
Comment (clalancette) [reply rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp]: > The rationale for calling `stop_execution(process_id);` explicitly is because there are inside of it a bunch or gtest checks which might fail and it would be better to have a clean backtrace where from it fails rather then generic failure from `scope_exit`

All right, that is a good reason to do it explicitly.

**Review by clalancette — APPROVED** [review]

**Review by james-rms — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Re-run CI with --retest-until-fail 5  after review.

BUILD args: --packages-above-and-dependencies rosbag2_test_common rosbag2_tests
TEST args: --packages-above rosbag2_test_common rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12033
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18708/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13234/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19440/)

**Comment by MichaelOrlov** [comment]
@clalancette Fair warning about or CI.  
I know that there are race condition in process destruction in this PR and `play_filters_by_topic` test fails every other time on my local machine. But our CI didn't catch it for Linux versions even with `--retest-until-fail 5`. And as you can see rpr job also passes green. 
This is not a first time I see that our CI not catching pretty obvious failures to witch it was pretty sensitive before (priore to the code freeze for Iron).
It looks like now we have pretty performant machines in CI and they are not very loaded with anything else.
IMO it should be some balanced load on CI infrastructure to catch corner cases and race conditions.

**Comment by MichaelOrlov** [comment]
Re-run CI with `--retest-until-fail 5` after addressing race condition in process destruction.

BUILD args: --packages-above-and-dependencies rosbag2_test_common rosbag2_tests
TEST args: --packages-above rosbag2_test_common rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12034
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18709/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13235/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19441/)

**Comment by MichaelOrlov** [comment]
@clalancette FYI I have fixed race conditions in process termination routines. Which was causing intermittent test failures due to sending SIGINT signal when the process was already in the destruction phase.
Now we will wait to finish rosbag2 play process instead of trying forcefully stop it.
See my latest commit https://github.com/ros2/rosbag2/pull/1297/commits/3af5b41f79d0043d4bde0dbd5f64b07f2ad0cafe for details.

**Comment by clalancette** [comment]
It looks like this probably needs some PUBLIC annotations for Windows CI to pass.

**Comment by MichaelOrlov** [comment]
@clalancette Nop. It's a bit more straightforward. The Windows build was failing because I start using wait_until_completion inside stop_execution and the former one was declared after the latter. I made a fix in the new commit.

Re-running CI for Windows.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19444/)

**Comment by MichaelOrlov** [comment]
@clalancette This PR has ABI and API changes in the test framework, although I want to backport it to the Iron branch if you wouldn't mind. It will help us to have a more stable CI for Iron.

**Comment by clalancette** [comment]
> @clalancette This PR has ABI and API changes in the test framework, although I want to backport it to the Iron branch if you wouldn't mind. It will help us to have a more stable CI for Iron.

Yeah, that should be fine here.

**Comment by MichaelOrlov** [comment]
Re-run Windows CI after fixing build errors. It was copy-past from Unix version and `process_id` shall be renamed to the `handle`

Re-running CI for Windows.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19452/)

**Comment by MichaelOrlov** [comment]
Re-running CI for Windows after fixing the compilation error from the previous run.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19455/)

**Comment by MichaelOrlov** [comment]
CI failed on Windows in the `test_rosbag2_play_end_to_end` with error message
```
C:\ci\ws\src\ros2\rosbag2\rosbag2_tests\test\rosbag2_tests\test_rosbag2_play_end_to_end.cpp(80): error: Expected equality of these values:
  future.wait_for(service_call_timeout_)
    Which is: 4-byte object <01-00 00-00>
  std::future_status::ready
    Which is: 4-byte object <00-00 00-00>
```
Line `test_rosbag2_play_end_to_end.cpp(80)` corresponds to the https://github.com/ros2/rosbag2/blob/3966c81ccf51bcd686d79328d02273ef9e265916/rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp#L80
Which means timeout for getting a response from a service call. The timeout is defined there as 4 seconds. It might be not enough for Windows.

**Comment by MichaelOrlov** [comment]
Re-running CI for Windows after increasing timeout for service call wait.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19458/)

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-05-18/31587/1
