### PR TITLE
Fix QoS overrides ignored when topic name has no leading slash

### LINKED ISSUE #1240: Allow QoS overrides for underqualified topic names
## Description

Followup from #1237 

QoS overrides for bag playback require the override topic name to exactly match the string topic name in the bag. However, ROS 2 names allow for different levels of qualifications, e.g. `my_topic`, and `/my_topic` are different exact strings, but expand to the same fully-qualified topic name `/my_topic`.

rosbag2 should compare only expanded topic names so that semantically-meaningless distinctions in user input are ignored.

https://design.ros2.org/articles/topic_and_service_names.html#ros-2-topic-and-service-name-constraints

## Completion Criteria

If a bag contains `/my_topic` and the QoS override specifies `my_topic`, the override should work. Likewise if the bag contains `my_topic`, then QoS override `/my_topic` should also work.

## Implementation Notes / Suggestions

Fully expand topic names before doing comparisons.

Maybe rosbag2 should fully expand all topic names when creating topics in storage?

## Testing Notes / Suggestions

Add a test for the new cases.

### PR DESCRIPTION
**Pull request by lakhmanisahil**
## Description

QoS override keys are compared against bag topic names using exact string matching. ROS 2 allows different levels of qualification for topic names `my_topic` and `/my_topic` are different strings but expand to the same fully-qualified name 
`/my_topic`. This means a user writing `talker:` in their YAML override file gets no match against `/talker` stored in the bag, and the override is silently ignored with no warning or error.

Fix: normalize topic names to their fully-qualified form (prepend `/` if absent) on both sides of the QoS override map — at insertion time in the constructor/`record()` and at lookup time in `publisher_qos_for_topic()` / `subscription_qos_for_topic()`.

Fixes #1240

### Is this user-facing behavior change?

Yes. Previously only an exact string match worked. Now both forms are accepted:

```yaml
# Before — only this worked if bag stores "/talker":
/talker:
  durability: transient_local

# After — both work:
talker:
  durability: transient_local
```

Likewise if the bag stores `my_topic`, then `/my_topic` in the YAML also works correctly now.

### Did you use Generative AI?

Yes, Claude Sonnet 4.6

### Additional Information

- Fix applies to both `ros2 bag play` (`player.cpp`) and `ros2 bag record` (`recorder.cpp`)
- If the name already starts with `/` or is empty it is returned   unchanged — no double-slash risk
- A new regression test `topic_qos_profile_override_matches_unqualified_name` is added to `test_play.cpp` to cover the case from the issue completion criteria
- Before/after screenshots attached showing `Durability: VOLATILE` (broken) vs `Durability: TRANSIENT_LOCAL` (fixed) with the same unqualified `talker:` YAML key

### Before

Screenshot from 2026-04-08 22-15-09

Screenshot from 2026-04-08 22-15-40

### After

Screenshot from 2026-04-09 00-30-57

### CODE REVIEW

**Review by MichaelOrlov — COMMENTED** [review]
@lakhmanisahil Thank you for your contribution.
I was under the impression that it would be possible to use already existent API for expanding topic names from rclcpp instead of manully try to detect if leading "`/`" is present or not in the topic name.

Can you please double check implementation of the API?
```cpp
std::string
expand_topic_or_service_name(
  const std::string & name,
  const std::string & node_name,
  const std::string & namespace_,
  bool is_service = false);
```
If we can use it to expand topic names?

**Comment by lakhmanisahil** [comment]
> If we can use it to expand topic names?

Thank you for the review @MichaelOrlov!

You're right, I see that `rclcpp::expand_topic_or_service_name()` is already used in the same constructor to normalize `topics_to_filter` and other filter lists. I should apply the same approach to the QoS override map keys instead of the manual slash-prefix check.

I'll update the implementation to use `rclcpp::expand_topic_or_service_name()` consistently and push a new version shortly.

**Comment by lakhmanisahil** [comment]
Hello @MichaelOrlov, I have updated the implementation to use `rclcpp::expand_topic_or_service_name()`.
PTAL. Thanks again for the guidance!

File: rosbag2_transport/src/rosbag2_transport/player.cpp [hunk 1]
```diff
@@ -60,6 +60,7 @@ namespace
  * \param topic_qos_profile_overrides A map of topic to QoS profile overrides.
  * @return The QoS profile to be used for subscribing.
  */
+
```
Comment (MichaelOrlov) [inline rosbag2_transport/src/rosbag2_transport/player.cpp]: Please remove this stray new line.

File: rosbag2_transport/src/rosbag2_transport/player.cpp [hunk 2]
```diff
@@ -547,7 +548,12 @@ PlayerImpl::PlayerImpl(
     starting_time_, std::chrono::steady_clock::now,
     std::chrono::milliseconds{100}, play_options_.start_paused);
   set_rate(play_options_.rate);
-  topic_qos_profile_overrides_ = play_options_.topic_qos_profile_overrides;
+  for (const auto & kv : play_options_.topic_qos_profile_overrides) {
+    topic_qos_profile_overrides_.emplace(
+    rclcpp::expand_topic_or_service_name(
+      kv.first, owner_->get_name(), owner_->get_namespace(), false),
+    kv.second);
+  }
```
Comment (MichaelOrlov) [inline rosbag2_transport/src/rosbag2_transport/player.cpp]: Address style for better readability and supportability
```suggestion
  
  // Expand topic names for overriding QoS profiles
  for (const auto & [topic_name, qos] : play_options_.topic_qos_profile_overrides) {
    auto expanded_topic_name =
      rclcpp::expand_topic_or_service_name(topic_name,
                                           owner_->get_name(),
                                           owner_->get_namespace(),
                                           false);
    topic_qos_profile_overrides_.emplace(expanded_topic_name, qos);
  }
```

File: rosbag2_transport/src/rosbag2_transport/recorder.cpp [hunk 3]
```diff
@@ -676,7 +676,12 @@ bool RecorderImpl::record(const std::string & uri)
   }
   RCLCPP_INFO(node->get_logger(), "Starting recording to '%s'", storage_options_.uri.c_str());
 
-  topic_qos_profile_overrides_ = record_options_.topic_qos_profile_overrides;
+  for (const auto & kv : record_options_.topic_qos_profile_overrides) {
+    topic_qos_profile_overrides_.emplace(
+    rclcpp::expand_topic_or_service_name(
+      kv.first, node->get_name(), node->get_namespace(), false),
+    kv.second);
+  }
```
Comment (MichaelOrlov) [inline rosbag2_transport/src/rosbag2_transport/recorder.cpp]: Please move this `topic_qos_profile_overrides_`  initialization into the constructor. 
To be consistent with other options' initialization. There is no reason to have initialization in the `record()`. This is some overlook from the past.
```suggestion
  // Expand topic names for overriding qos profiles
  for (const auto & [topic_name, qos] : record_options_.topic_qos_profile_overrides) {
    auto expanded_topic_name =
      rclcpp::expand_topic_or_service_name(topic_name,
                                           node->get_name(),
                                           node->get_namespace(),
                                           false);
    topic_qos_profile_overrides_.emplace(expanded_topic_name, qos);
  }
```

File: rosbag2_transport/src/rosbag2_transport/recorder.cpp [hunk 4]
```diff
@@ -1868,7 +1875,7 @@ rclcpp::QoS RecorderImpl::subscription_qos_for_topic(const std::string & topic_n
           "repeat-transient-local will not work unless the override includes transient_local "
           "durability.");
     }
-    return topic_qos_profile_overrides_.at(topic_name);
+    return topic_qos_profile_overrides_.at(expanded);
```
Comment (MichaelOrlov) [inline rosbag2_transport/src/rosbag2_transport/recorder.cpp]: Please rename `expanded` to a full name `expanded_topic_name` and use it in the logging and
```cpp
if (record_options_.repeat_transient_local_messages.count(topic_name) > 0 &&
      topic_qos_profile_overrides_.at(topic_name).get_rmw_qos_profile().durability !=
      RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL)
```
to avoid inconsistency.

File: rosbag2_transport/test/rosbag2_transport/test_play.cpp [hunk 5]
```diff
@@ -2503,6 +2503,28 @@ TEST_F(RosBag2PlayQosOverrideTestFixture, topic_qos_profiles_overridden)
...
+  const auto qos_request = rclcpp::QoS{rclcpp::KeepAll()}.reliable().transient_local();
+  const auto qos_playback_override = rclcpp::QoS{rclcpp::KeepAll()}.reliable().transient_local();
+  // Strip the leading slash to simulate a user writing "my_topic" instead of "/my_topic" in YAML
+  ASSERT_FALSE(topic_name_.empty());
+  ASSERT_EQ(topic_name_.front(), '/');
+  const std::string unqualified_name = topic_name_.substr(1);
+  const auto topic_qos_profile_overrides = std::unordered_map<std::string, rclcpp::QoS>{
+    std::pair<std::string, rclcpp::QoS>{unqualified_name, qos_playback_override},
+  };
+  const auto timeout = 5s;
```
Comment (MichaelOrlov) [inline rosbag2_transport/test/rosbag2_transport/test_play.cpp]: Please increase the timeout to 10 sec. Sometimes, 5 seconds is not enough for our CI.
```suggestion
  const auto timeout = 10s;
```

**Review by MichaelOrlov — CHANGES_REQUESTED** [review]
@lakhmanisahil Thank you for your contribution.
Please see my comments inline.

File: rosbag2_transport/src/rosbag2_transport/player.cpp (hunk 2 above)
Comment (lakhmanisahil) [reply rosbag2_transport/src/rosbag2_transport/player.cpp]: Done, updated 👍

**Comment by lakhmanisahil** [comment]
Hello @MichaelOrlov, I’ve addressed your feedback and pushed the updates. PTAL.
I’ll update the PR description after the final changes. Thank You

**Comment by lakhmanisahil** [comment]
After rebasing, I see that this file was included in my PR, but it doesn’t seem related to my changes:
`rosbag2_transport/test/rosbag2_transport/test_record_services.cpp`

Should I drop it from this branch?

**Comment by MichaelOrlov** [comment]
@lakhmanisahil It seems instead of doing a rebase, you did a merge of the rolling into your branch, and that didn't go well. Somehow, you picked up one extra commit https://github.com/ros2/rosbag2/pull/2394/changes/92fccddd6ecac5b4ac78e842d94e5d9c866beab4 in your delta.

**Review by MichaelOrlov — APPROVED** [review]
@lakhmanisahil I've fixed your branch and pushed one commit. Please update your local branch after fetch.
LGTM with green CI.

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2394
Gist: https://gist.githubusercontent.com/MichaelOrlov/fd42cddc63cd044eeeb480f55cece148/raw/5d7deaf7e5caebcf15f8b84f7e720187dd9b1f18/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport
TEST args:  --packages-above rosbag2_transport
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18964
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/28723/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/21543/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/8561/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/27590/)

**Comment by lakhmanisahil** [comment]
Hi @MichaelOrlov, thank you for approving this PR.
Is there anything else that needs to be addressed, or is it ready to be merged and the issue closed?

**Comment by MichaelOrlov** [comment]
Hi @lakhmanisahil. Thank you for your contribution.
No worries, all good. I was waiting a couple of days until the Rolling release goes through.
I am merging it now.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted jazzy
