### PR TITLE
Fix for multibag replay stagnation

### LINKED ISSUE #2156: When using multibag replay, the frequency of the messages on topics is reduced and inconsistent over the time
## Description
When using multibag replay, the frequency of the messages on topics is reduced compared to when the bags are replayed individually.
The issue notably reproduces after some time of playback when one of the bags has topics with significantly lower frequency, rather than topics in the other bags.

### Expected Behavior
The playback from the multiple bags shall be consistent without starvation and stagnation, even if some topics have a significantly lower frequency than others.

### Actual Behavior
The frequency of the messages on topics is reduced when one of the bags has topics with significantly lower frequency, rather than topics in the other bags.

## To Reproduce
1. Create a bag with topic1 with frequency 10 Hz and length around 3-5 minutes
2. Create a bag with topic2 with frequency 20 Hz and with the same length around 3-5 minutes
3. replay bags with CLI `ros2 bag play -r -i /path/to/bag1 -i /path/to/bag2`
4. Subscribe to topic2 with `topic hz /topic2` CLI
5. After a few minutes, observe publishing rate degradation on the `topic2`

## System (please complete the following information)
 - OS: Ubuntu 14.04
 - ROS 2 Distro: Rolling, Kilted, Jazzy
 - Install Method: Build from source
 - Version: https://github.com/ros2/rosbag2/commit/0d376929963348387d0e13ba7e90f2d642fc4fa1

## Additional context
** Add any other context about the problem here **

### PR DESCRIPTION
**Pull request by MichaelOrlov**
## Description

This PR fixes a problem for slow playback when one reader has a lower frequency topic than others

- Added cache for the last element from each reader and taking messages from cache in a chronological order instead of the round-robin order.
- To mitigate "spaggetish" code after the fix, this PR also introduces the `ReadersWrapper` class, which will encapsulate readers with their options and message cache.
- The `ReadersWrapper` class manages multiple `rosbag2_cpp::Reader` instances, allowing for chronological reading of messages across all readers. It maintains a cache of the next message from each reader and provides methods to retrieve the next message in chronological order, seek to a specific timestamp across all readers, and apply filters to all readers. It also provides access to the earliest and latest timestamps across all readers.

- Fixes #2156
- Depends on the #2157 

### Is this user-facing behavior change?
Fixed a bug where playback of the higher frequency topics can slow down when present slow frequency topics in another playing bag.

### Did you use Generative AI?
Yes. I am using GitHub Copilot, GPT-4.1, in my workflow. in particular to help with unit tests and documentation.

### Additional Information
This PR can be backported to the other distros.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2158
Gist: https://gist.githubusercontent.com/MichaelOrlov/15d3a9082ed76aa64911d78bc47d74f7/raw/bc34f98f1ab92956f6be1d973f053311a2f6ec79/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport rosbag2_tests
TEST args:  --packages-above rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16834
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24744/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18773/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4194/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25260/)

File: rosbag2_transport/include/rosbag2_transport/readers_wrapper.hpp [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+class ReadersWrapperImpl;
+
+/// \class ReadersWrapper
+/// \brief This class manages multiple rosbag2_cpp::Reader instances, allowing for
+/// chronological reading of messages across all readers.
+/// \details It maintains a cache of the next message from each reader and provides methods to
+/// retrieve the next message in chronological order, seek to a specific timestamp across all
+/// readers, and apply filters to all readers. It also provides access to the earliest and
+/// latest timestamps across all readers.
+class ROSBAG2_TRANSPORT_PUBLIC ReadersWrapper
```
Comment (fujitatomoya) [inline rosbag2_transport/include/rosbag2_transport/readers_wrapper.hpp]: Just a minor suggestion. How about naming the class `ReaderManager` would provide clearer intent, as the class is responsible for managing multiple `rosbag2_cpp::Reader` instances such as opening, seeking, filtering, and reading messages chronologically. IMO "Wrapper" sounds more general pattern and doesn’t convey what the class actually does, while "Manager" directly indicates its role in handling and coordinating the readers?

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI.

File: rosbag2_transport/include/rosbag2_transport/readers_wrapper.hpp (hunk 1 above)
Comment (MichaelOrlov) [reply rosbag2_transport/include/rosbag2_transport/readers_wrapper.hpp]: @fujitatomoya Thank you for your review. Your suggestion about renaming to the `ReadersManager` does make sense to me. I will go ahead and rename it.

**Comment by MichaelOrlov** [comment]
Re-run CI after renames
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16837
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24747/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18776/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4198/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25264/)

**Comment by MichaelOrlov** [comment]
Hold off from merging this PR. We have regression in the tests under the load
```bash
/tmp/ws/src/rosbag2/rosbag2_transport/test/rosbag2_transport/test_play_seek.cpp:144: Failure
Expected equality of these values:
  replayed_topic1[2]->int32_value
    Which is: 4
  1

/tmp/ws/src/rosbag2/rosbag2_transport/test/rosbag2_transport/test_play_seek.cpp:145: Failure
Expected equality of these values:
  replayed_topic1[3]->int32_value
    Which is: 1
  2
```

### Preliminary analysis
That is because a data race for the internal queue cleanup and refill.
Before, the queue cleanup and refill was protected by the `readers_mutex`; now I moved those mutex inside `ReadersManager`, and when we are doing `seek()` we need to do `queue->purge()` and readers->seek(timestamp). However, another thread still trying to refill the queue from the readers in the background.

**Comment by MichaelOrlov** [comment]
Note: Decided to move a couple of commits 
-  [Fix multiple race conditions in the play_messages_from_queue()](https://github.com/ros2/rosbag2/pull/2158/commits/48fa0bc8c1877ba8e3e966757fd6469f06d17aa0)
- [Wait for Player->play() to be called in the wait_for_playback_to_start()](https://github.com/ros2/rosbag2/pull/2158/commits/7ec6449a75373765133c01d18ffa4bd02f3f736e)
to the follow-up PR, since they are unrelated to the original fix and could be merged separately.

**Comment by MichaelOrlov** [comment]
Re-run CI
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16885
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24800/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18829/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4250/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25312/)

**Comment by MichaelOrlov** [comment]
The Linux-RHEL CI job failed due to not found Uncrustify.
Trying to re-run this job
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4259/)

**Comment by MichaelOrlov** [comment]
@mjcarroll @ahcorde Any ideas for why [RHEL CI job](https://ci.ros2.org/job/ci_linux-rhel/4259/#showFailuresLink) keep fails?  
Something is wrong with uncrustify.  
I am curious if it is somehow related to the recent removal of the `uncrustify_vendor` package.

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2158
Gist: https://gist.githubusercontent.com/MichaelOrlov/2ba68fbf0fbdc4a9da5643bfca61fc85/raw/bc34f98f1ab92956f6be1d973f053311a2f6ec79/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport rosbag2_tests
TEST args:  --packages-above rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16939
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24858/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18891/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4313/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25369/)

**Comment by MichaelOrlov** [comment]
The RHEL CI job failed due to the CI infrastructure issue. It was auto-restarted and passed green
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4314/)

**Comment by MichaelOrlov** [comment]
The CI is green after reverting the `uncrustify_vendor` removal. Merging then.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted jazzy
