### PR TITLE
Check for nullptrs when pushing new messages to the message cache

### LINKED ISSUE #2115: Lack of Null Pointer Checks in MessageCacheCircularBuffer::push Causes Crash
## Description
The MessageCacheCircularBuffer::push function does not validate whether the input message pointer is null

### Expected Behavior
no crash

### Actual Behavior
crash

### Test Case
```cpp
#include <gtest/gtest.h>
#include <memory>
#include "rosbag2_cpp/cache/message_cache_circular_buffer.hpp"
using namespace rosbag2_cpp::cache;
class MessageCacheCircularBufferTest : public testing::Test {
protected:
  MessageCacheCircularBufferTest() : buffer_(1024) {}  
  MessageCacheCircularBuffer buffer_;
};

TEST_F(MessageCacheCircularBufferTest, PushNullptrCausesCrash) {
  ASSERT_THROW({
    buffer_.push(nullptr);
  }, std::exception); 
}

```

### Output
```markdown
==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MessageCacheCircularBufferTest
[ RUN      ] MessageCacheCircularBufferTest.PushNullptrCausesCrash
AddressSanitizer:DEADLYSIGNAL
=================================================================
==50347==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x77fb2f79c05c bp 0x7ffe5a9352f0 sp 0x7ffe5a9352f0 T0)
==50347==The signal is caused by a READ memory access.
==50347==Hint: address points to the zero page.
    #0 0x77fb2f79c05c in std::__shared_ptr<rcutils_uint8_array_s, (__gnu_cxx::_Lock_policy)2>::get() const (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x19c05c) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #1 0x77fb2f79bd01 in std::__shared_ptr_access<rcutils_uint8_array_s, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x19bd01) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #2 0x77fb2f79bafb in std::__shared_ptr_access<rcutils_uint8_array_s, (__gnu_cxx::_Lock_policy)2, false, false>::operator->() const (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x19bafb) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #3 0x77fb2f79c999 in rosbag2_cpp::cache::MessageCacheCircularBuffer::push(std::shared_ptr<rosbag2_storage::SerializedBagMessage const>) (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x19c999) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f)
    #4 0x5e16f41c54a7 in MessageCacheCircularBufferTest_PushNullptrCausesCrash_Test::TestBody() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xad4a7) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #5 0x5e16f42663df in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0x14e3df) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #6 0x5e16f42534eb in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0x13b4eb) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #7 0x5e16f41f8be9 in testing::Test::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xe0be9) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #8 0x5e16f41fa3c5 in testing::TestInfo::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xe23c5) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #9 0x5e16f41fb71e in testing::TestSuite::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xe371e) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #10 0x5e16f4222449 in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0x10a449) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #11 0x5e16f426983a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0x15183a) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #12 0x5e16f4256788 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0x13e788) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #13 0x5e16f421ea53 in testing::UnitTest::Run() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0x106a53) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #14 0x5e16f41c8ef4 in RUN_ALL_TESTS() (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xb0ef4) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #15 0x5e16f41c8e40 in main (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xb0e40) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)
    #16 0x77fb2d62a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #17 0x77fb2d62a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #18 0x5e16f41c5234 in _start (/home/shangzh/rosbag2_ws/build/rosbag2_cpp/test_circular_message_cache+0xad234) (BuildId: 54ffc90f21d2cdccd50220554d13d915b9679ba9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/shangzh/ros2_jazzy/install/rosbag2_cpp/lib/librosbag2_cpp.so+0x19c05c) (BuildId: 3d08948fe755a0c3db5601d87d0d7a6d5d33654f) in std::__shared_ptr<rcutils_uint8_array_s, (__gnu_cxx::_Lock_policy)2>::get() const
==50347==ABORTING

```

## System (please complete the following information)
OS: ubuntu 24.04
ROS 2 Distro: ros 2 jazzy
Install Method: source
Version: ros 2 jazzy
build options: --mixin asan-gcc

### PR DESCRIPTION
**Pull request by jncfa**
## Description

Adds a simple check to the message cache circular buffer when pushing nullptr messages.
Changed CircularMessageCache to report when dropping messages (null or too large for buffer).

- Fixes #2115

### Is this user-facing behavior change?

As it only adds a check if the message is a nullptr, this should not change any normal runtime behavior as this should always trigger a segmentation fault or at minimum UB.

### Did you use Generative AI?

No

### CODE REVIEW

File: rosbag2_cpp/src/rosbag2_cpp/cache/circular_message_cache.cpp [hunk 1]
```diff
@@ -42,6 +42,10 @@ CircularMessageCache::~CircularMessageCache()
 
 bool CircularMessageCache::push(std::shared_ptr<const rosbag2_storage::SerializedBagMessage> msg)
 {
+  if (msg == nullptr) {
+    return false;
+  }
```
Comment (christophebedard) [inline rosbag2_cpp/src/rosbag2_cpp/cache/circular_message_cache.cpp]: I'd like to hear what @MichaelOrlov thinks, because there's a note in the method documentation that says this always returns true: https://github.com/ros2/rosbag2/blob/73b50297184d099f60d9d377844090bb87f405f8/rosbag2_cpp/include/rosbag2_cpp/cache/circular_message_cache.hpp#L61-L62

**Review by MichaelOrlov — CHANGES_REQUESTED** [review]
Sorry, but Nop. Not this way at least.  
Please refer to my original response in the relevant issue https://github.com/ros2/rosbag2/issues/2115#issuecomment-3316386076.

In essence, if we return false from the push method, it means that the message was lost, and this message drop will be reported on the upper layer and will be counted in statistics. This is incorrect because `CircularMessageCache` drops messages by design when the message queue is full, and we should not report messages lost on the upper layer.

**Comment by jncfa** [comment]
> Sorry, but Nop. Not this way at least. Please refer to my original response in the relevant issue [#2115 (comment)](https://github.com/ros2/rosbag2/issues/2115#issuecomment-3316386076).
> 
> In essence, if we return false from the push method, it means that the message was lost, and this message drop will be reported on the upper layer and will be counted in statistics. This is incorrect because `CircularMessageCache` drops messages by design when the message queue is full, and we should not report messages lost on the upper layer.

is throwing more reasonable or would you rather just not have this in at all? asking since you already closed the original issue for it

if you don't see any added value by adding an exception with a custom message I'll just close the PR

**Comment by MichaelOrlov** [comment]
Hi @jncfa, I've just spent some time making a deeper analysis of the CircularCache and its underlying CircularBuffer.
It doesn't make sense to check for nullptr inside the `CircularMessageCache::push()` since we are not dereferencing it there.
However, it does make sense to check for nullprt inside `bool MessageCacheCircularBuffer::push(CacheBufferInterface::buffer_element_t msg)` where we are dereferencing those shared pointer. 
Since we already have code that drops messages in the `MessageCacheCircularBuffer::push(..)` due to the message size exceeding the snapshot buffer size. Could you please do the following:
1. Remove check for nullptr in the `CircularMessageCache::push(..)`
2. Change `CircularMessageCache::push(..)` to return a result of the underlying push method from the producer.
   ```
     bool CircularMessageCache::push(std::shared_ptr<const rosbag2_storage::SerializedBagMessage> msg)
     {
       std::lock_guard<std::mutex> cache_lock(producer_buffer_mutex_);
       return producer_buffer_->push(msg);
     }
   ```
4. Add check for nullptrs in the `MessageCacheCircularBuffer::push`
   ```
   bool MessageCacheCircularBuffer::push(CacheBufferInterface::buffer_element_t msg)
    {
      if (!msg || !msg->serialized_data) {
        ROSBAG2_CPP_LOG_ERROR("Attempted to push null message into circular buffer. Dropping message!");
        return false;
      }
      // Drop message if it exceeds the buffer size
      if (msg->serialized_data->buffer_length > max_bytes_size_) {
        ROSBAG2_CPP_LOG_WARN("Last message exceeds snapshot buffer size. Dropping message!");
        return false;
      }
    ...
   ```

**Review by MichaelOrlov — COMMENTED** [review]
@jncfa Thanks for the follow-up.
Now looks good with one minor adjustment. Can you please update Doxygen comments for the push methods in the header files?

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Review by MichaelOrlov — APPROVED** [review]
Note: I've pushed a commit with an update for Doxygen comment for the MessageCacheCircularBuffer::push(msg)

LGTM now.

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2219
Gist: https://gist.githubusercontent.com/MichaelOrlov/c0c727e3961554cb0fa3eab85317008d/raw/80dbb32d7ca07ecee7f30299c9587f31a4c3b910/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_cpp
TEST args:  --packages-above rosbag2_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17409
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/25621/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19654/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/5177/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25850/)

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted jazzy
