### PR TITLE
include hidden topics

### LINKED ISSUE #331: ros2 bag record -a records also hidden topics
## Description
When calling `ros2 bag record -a`, really all topics are recorded. This includes also hidden topics. 
This became a problem while developing rosbag support for `rmw_iceoryx_cpp` in which there are reserved internal topics, which don't have an appropriate message definition and thus can't be recorded.
For more details see: https://github.com/ros2/rmw_iceoryx/issues/13

### Expected Behavior
Hidden topics are not recorded by default for the above mentioned reasons.

### Actual Behavior
rosbag2 is crashing due to not finding appropriate message definition packages.

## Additional context
An ideal solution would be to have an option `--include-hidden-topics` which explicitly records the internal topics as well.

### PR DESCRIPTION
**Pull request by Karsten1987**
closes #331 

This change introduces a new command line option `--include-hidden-topics` which explicitly enables the recording of hidden topics. If this option is not set, hidden topics won't be recored by default.

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

File: rosbag2_transport/src/rosbag2_transport/rosbag2_node.cpp [hunk 1]
```diff
@@ -149,24 +151,44 @@ std::unordered_map<std::string, std::string> Rosbag2Node::get_topics_with_types(
...
+    if (!include_hidden_topics) {
+      auto tokens = rcpputils::split(topic_and_type.first, '/', true);  // skip empty
+      auto is_hidden = std::find_if(tokens.begin(), tokens.end(), [](const auto & token) -> bool {
+          return token[0] == '_';
+          });
+      if (is_hidden != tokens.end()) {
+        ROSBAG2_TRANSPORT_LOG_ERROR_STREAM(
+          "Hidden topics are not recorded. Topic '" <<
+            topic_and_type.first << "' will be skipped." <<
+            "You can enable them with --include-hidden-topics");
```
Comment (Karsten1987) [inline rosbag2_transport/src/rosbag2_transport/rosbag2_node.cpp]: Since this is polled periodically, I am looking for a way to log only once. I am currently unable to find the appropriate macro, any ideas?

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9791/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5413/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7957/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9651/)

File: rosbag2_transport/src/rosbag2_transport/rosbag2_node.cpp [hunk 2]
```diff
@@ -149,24 +151,44 @@ std::unordered_map<std::string, std::string> Rosbag2Node::get_topics_with_types(
...
+        RCLCPP_WARN_ONCE(
+          rclcpp::get_logger("rosbag2_transport"),
+          "Hidden topics are not recorded. Enable them with --include-hidden-topics");
+        continue;
+      }
     }
+
+    filtered_topics_and_types.insert({topic_and_type.first, topic_and_type.second[0]});
   }
+
```
Comment (emersonknapp) [inline rosbag2_transport/src/rosbag2_transport/rosbag2_node.cpp]: nit: unecessary newline

**Comment by Karsten1987** [comment]
thanks for the iteration!
