### PR TITLE
Bugfix: Player can't play with read_ahead_queue_size equal 1

### LINKED ISSUE #2168: No messages are read with --read-ahead-queue-size 1
## Description
When a rosbag is played back with `--read-ahead-queue-size 1`, no messages are played.  This results from the calculation
```
auto queue_lower_boundary =
    static_cast<size_t>(play_options_.read_ahead_queue_size * read_ahead_lower_bound_percentage_);
```
which rounds to 0 in the case of `play_options_.read_ahead_queue_size == 1`

This could be fixed by handling the edge case, setting the lower bound to 1 when it rounds to 0.

### Expected Behavior
A single message is queued at a time, and messages are played on their respective topics.

### Actual Behavior
The player hangs, playing no messages, as it continues waiting for messages to be loaded from the bag but the loading thread never retrieves them.

## To Reproduce
Play back a rosbag with
`ros2 bag play --read-ahead-queue-size 1 <bag_file>`

## System (please complete the following information)
 - OS: Ubuntu Jammy
 - ROS 2 Distro:  Humble onwards (at least), but more important from Jazzy
 - Install Method: N/A
 - Version: N/A

### PR DESCRIPTION
**Pull request by MichaelOrlov**
## Description

Bugfix: for the situation when Player can't play with `--read-ahead-queue-size` or `rosbag2_transport::PlayOptions::read_ahead_queue_size` equal 1.

- Fixes #2168 

### Is this user-facing behavior change?
Yes. User will be able to use playback with `--read-ahead-queue-size 1` CLI option.

### Did you use Generative AI?
Yes. I am using GitHub Copilot, GPT-4.1 in my workflow.

### Additional Information
The fix can be backported

### CODE REVIEW

File: rosbag2_transport/test/rosbag2_transport/test_play.cpp [hunk 1]
```diff
@@ -403,6 +403,76 @@ TEST_F(RosBag2PlayTestFixture, recorded_messages_are_played_for_all_topics)
           ElementsAre(40.0f, 2.0f, 0.0f)))));
 }
 
+TEST_F(RosBag2PlayTestFixture, can_play_messages_with_queue_size_equeal_one)
```
Comment (christophebedard) [inline rosbag2_transport/test/rosbag2_transport/test_play.cpp]:
```suggestion
TEST_F(RosBag2PlayTestFixture, can_play_messages_with_queue_size_equal_one)
```

**Review by christophebedard — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#2174
Gist: https://gist.githubusercontent.com/MichaelOrlov/19166961315f0bbe8b108623fb6d66b8/raw/617a37b11c768d05962a95f70badd125b59774d0/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport rosbag2_tests
TEST args:  --packages-above rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17025
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24954/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19050/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4429/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25456/)

**Comment by MichaelOrlov** [comment]
CI failed due to the massive CI infrastructure outage with errors like 
```bash
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/noble-security/universe/binary-arm64/Packages.gz  File has unexpected size (1110837 != 1110832). Mirror sync in progress? [IP: 91.189.91.104 80]
16:11:08    Hashes of expected file:
16:11:08     - Filesize:1110832 [weak]
16:11:08     - SHA256:5b61d1eb2248baeaca320473c80afb8df1c095dcebf56a8fde807161310ca5a5
16:11:08     - SHA1:26f9e3570aef58d2369665d69340058955dbcfa4 [weak]
16:11:08     - MD5Sum:eb3de2c6410ab8862c6d2bfc9cccccc3 [weak]
16:11:08    Release file created at: Thu, 18 Sep 2025 19:28:46 +0000
16:11:08 E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Two CI jobs auto-restarted and passed green
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24985/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4460/)

**Comment by MichaelOrlov** [comment]
re-run 
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19062/)

**Comment by MichaelOrlov** [comment]
The CI has not been doing very well in the last few days. The failed Ci job auto-restarted and passed green
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19063/)
Therefore, all the CI pipelines are green now.
Merging then.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport kilted jazzy
